import styles from "../documents.module.css";
import { systemFunctionCatalog } from "./SystemAnalysisFunctionCatalog";

type FunctionSpec = {
  id: string;
  workflow: string;
  preconditions: string;
  validation: string;
  algorithm: string[];
  failures: string;
  test: string;
};

const sp = (id: string, workflow: string, preconditions: string, validation: string, algorithm: string[], failures: string, test: string): FunctionSpec => ({ id, workflow, preconditions, validation, algorithm, failures, test });

const modulePolicies: Record<string, { security: string; performance: string; observability: string }> = {
  "MOD-01": { security: "Public read; ຫ້າມຮົ່ວ Draft/PII ແລະຕ້ອງ escape external metadata.", performance: "Cursor pagination; pageSize ມີ ceiling; query ບໍ່ຄວນ N+1.", observability: "ວັດ latency, eligible count, fallback rate ແລະ cursor rejection." },
  "MOD-02": { security: "Normalize/limit query; ຫ້າມນຳ raw query ໄປຕໍ່ SQL/HTML.", performance: "Indexed search/filter; deterministic cursor; timeout ບໍ່ block page.", observability: "ວັດ search latency, zero-result rate, invalid filter ແລະ result count." },
  "MOD-03": { security: "Public read/action payload ສ້າງຈາກ trusted Place data; canonical URL ເທົ່ານັ້ນ.", performance: "Composite read ຕ້ອງ batch; external action ບໍ່ລໍຖ້າ analytics.", observability: "ວັດ detail latency, redirect, unavailable action, external fallback ແລະ intent." },
  "MOD-04": { security: "Admin command ຕ້ອງ authorize; URL/domain allowlist; ຫ້າມ download/re-host media.", performance: "External check ມີ timeout/retry; ຫ້າມຖື DB transaction ລະຫວ່າງ network call.", observability: "ວັດ validation class, platform latency, retry, duplicate URL ແລະ takedown SLA." },
  "MOD-05": { security: "Admin-only write; expected-version; critical change ມີ evidence/reason/Audit.", performance: "Indexed identity/contact/location; merge ລັອກຕາມ canonical order ແລະຈຳກັດ transaction.", observability: "ວັດ publish blocker, conflict, merge duration, moved relation count ແລະ rollback." },
  "MOD-06": { security: "Protect requester contact/evidence; authorize decision; ຫ້າມເປີດ PII ໃນ log/analytics.", performance: "Queue paginate/index status+due; communication ສົ່ງຫຼັງ commit.", observability: "ວັດ acknowledgment/decision SLA, needs-evidence time, partial/rejected items." },
  "MOD-07": { security: "Admin-only write; agreement reference protected; Sponsored ບໍ່ປ່ຽນ Trust.", performance: "Index status/time/placement; scheduler ປະມວນແຍກ campaign.", observability: "ວັດ activation blocker, active duration, impression/open/intent ແລະ data-quality flag." },
  "MOD-08": { security: "Authentication + authorization ບັງຄັບ; no shared account; Audit append-only.", performance: "Session lookup/cache ມີ revocation check; queue paginate; audit insert ຢູ່ domain transaction.", observability: "ວັດ auth failure, deny, stale session, queue latency ແລະ audit rollback." },
  "MOD-09": { security: "Consent/allowlist; anonymous ID; ຫ້າມ PII/fingerprinting ແລະ partner ຫ້າມເຫັນ session rows.", performance: "Event ingest ສັ້ນ; unique keys ກັນ retry; report ໃຊ້ aggregate/index.", observability: "ວັດ accepted/rejected/duplicate events, ingest latency, definition version ແລະ report quality." },
  "MOD-10": { security: "Scheduler identity/lease; Admin decision authorize; automated job ຫ້າມ override takedown.", performance: "Batch/claim ແບບຈຳກັດ; unique open work item; external recheck ນອກ transaction.", observability: "ວັດ due/stale backlog, claim retry, verification completion, source restore/blocker." },
};

const specs: FunctionSpec[] = [
  sp("FN-FEED-001", "WF-01-01", "Feed service ພ້ອມ; cursor ບໍ່ຖືກ tamper.", "pageSize 1–50; category active; cursor decode/version valid.", ["Normalize request ແລະ resolve cursor", "ເອີ້ນ FN-FEED-002 ເພື່ອຫາ candidates", "ເອີ້ນ FN-FEED-003 ສ້າງ item ຈົນຄົບ pageSize+1", "ສົ່ງ items ແລະ nextCursor ຖ້າມີລາຍການຕໍ່"], "Invalid cursor → restart-required; store timeout → retryable unavailable.", "Given mixed states, response ມີສະເພາະ eligible items, ບໍ່ເກີນ pageSize ແລະ cursor ບໍ່ຊ້ຳ."),
  sp("FN-FEED-002", "WF-01-01", "Place/Source/Campaign states ອ່ານໄດ້.", "currentTime server-side; candidate IDs valid.", ["Query Published Places ທີ່ມີ Published/Available Source", "ຕັດ Removed/Takedown/Archived/Suspended", "ຜູກ Active Campaign ສະເພາະໃນໄລຍະ", "ຈັດ stable ordering ແລະສົ່ງ candidate IDs"], "No candidate → empty list; inconsistent state → exclude + quality signal.", "Draft, expired campaign ແລະ unavailable source ບໍ່ຜ່ານ; active sponsored candidate ມີ campaign ID."),
  sp("FN-FEED-003", "WF-01-01", "placeId/sourceId eligible ແລ້ວ.", "IDs ກົງຄູ່; attribution/canonical URL ຄົບ.", ["Batch-read Place/Creator/Source/Campaign", "Resolve independent trust/freshness/partner/sponsored labels", "Map ເປັນ FeedItem contract ໂດຍບໍ່ສົ່ງ internal fields", "Escape metadata ແລະສົ່ງ normalized item"], "Missing required relation → skip item + data-quality signal.", "Output ມີ Place ID, source attribution, canonical links; paid label ບໍ່ປ່ຽນ verified label."),
  sp("FN-FEED-004", "WF-01-01", "nextCursor ມາຈາກ feed response.", "cursor signature/version/expiry valid.", ["Decode cursor", "ສ້າງ request ດ້ວຍ ordering key ຫຼັງສຸດ", "ເອີ້ນ FN-FEED-001", "ກວດ first item ບໍ່ຊ້ຳກັບ boundary ເກົ່າ"], "Expired/tampered cursor → invalid-cursor; no more → empty + null cursor.", "ສອງ page ຕໍ່ກັນບໍ່ມີ ID ຊ້ຳ ແລະ ordering ຄົງທີ່."),
  sp("FN-FEED-005", "WF-01-01", "FeedItem ມີ source URL/creator.", "embed/preview URL ຕ້ອງ trusted protocol/domain.", ["ກວດ device/embed capability", "ພະຍາຍາມ official embed", "ຖ້າລົ້ມສະແດງ preview/attribution/source link", "ບັນທຶກ fallback metric ໂດຍບໍ່ປ່ຽນ Source state"], "Embed blocked/timeout → fallback; unsafe URL → text-only attribution.", "Embed success ແລະ failure ຕ້ອງເປີດ Place/Source ໄດ້; ບໍ່ມີ media re-host."),

  sp("FN-SRCH-001", "WF-02-01", "locale ຮອງຮັບ.", "rawQuery ຄວາມຍາວບໍ່ເກີນ limit; string UTF-8.", ["Trim/collapse whitespace", "normalize Unicode/case ຕາມ locale", "tokenize ໂດຍຮັກສາຄວາມໝາຍ", "ສົ່ງ normalizedQuery + tokens"], "Too long/control chars → validation error; empty → browse mode.", "ຄຳລາວ/ອັງກິດທີ່ຄວາມໝາຍດຽວ normalize ຄົງທີ່; input ບໍ່ຖືກ execute."),
  sp("FN-SRCH-002", "WF-02-01", "Search read model ພ້ອມ.", "query/cursor/pageSize valid.", ["ເອີ້ນ FN-SRCH-001", "Match name/alias/search terms", "Recheck Place Published", "ເອີ້ນ filter/order ແລະສົ່ງ summaries+cursor"], "Index unavailable → retryable search error; invalid cursor → restart.", "Draft/Suspended ບໍ່ອອກ; alias ຄົ້ນພົບ canonical Place; page ບໍ່ຊ້ຳ."),
  sp("FN-SRCH-003", "WF-02-01", "Candidate set ຈາກ Published Places.", "Category/Area active; price min≤max; unknown filter rejected.", ["Resolve filter IDs", "Apply OR ພາຍໃນ group", "Apply AND ລະຫວ່າງ category/area/price groups", "ສົ່ງ filtered IDs ແລະ active filter echo"], "Invalid filter → field error; zero match → empty set.", "Filter combinations ໄດ້ expected intersection; Unknown price ບໍ່ຜ່ານ price filter."),
  sp("FN-SRCH-004", "WF-02-01", "Matching candidates ມີ relevance features.", "Sponsored context active/eligible; deterministic tie-break ID.", ["ຄຳນວນ organic relevance", "ເລືອກ active sponsored slot ແຍກ", "Interleave ຕາມ placement policy ພ້ອມ label", "Sort tie ດ້ວຍ stable key"], "Missing label/expired campaign → treat organic ຫຼື exclude paid placement.", "Same input ໄດ້ same order; sponsored result ມີ label/campaign ID; verified score ບໍ່ປ່ຽນ."),
  sp("FN-SRCH-005", "WF-02-01", "Search result count = 0.", "query/filter state parseable.", ["ກວດ filter ທີ່ຈຳກັດຫຼາຍ", "ສ້າງ clear-one/clear-all actions", "ເລືອກ active suggested categories", "ສົ່ງ explicit empty response"], "Category lookup fail → clear-filter only.", "Empty response ບໍ່ມີ fake match; action ສາມາດສ້າງ valid next search."),

  sp("FN-PLC-001", "WF-03-01", "slug/ID format valid.", "Resolve redirect ກ່ອນ; public read Published only.", ["ເອີ້ນ FN-PADM-010", "Read Place + category/area/contact/hours/price", "ເອີ້ນ FN-PLC-002—004", "Map composite PlaceDetail ຫຼື redirect/not-found"], "Unknown/non-public → not-found; child data conflict → omit unsafe field + quality label.", "Canonical Place returns complete contract; merged slug redirects; Draft data ບໍ່ຮົ່ວ."),
  sp("FN-PLC-002", "WF-03-01", "Canonical Published Place.", "source.place_id matches; status Published+Available.", ["Query Source by place_id", "Filter takedown/unavailable/removed", "Join Creator attribution", "Sort by approved source order/checked date"], "Missing creator/URL → exclude + quality signal.", "ທຸກ output source ມີ creator/platform/canonical URL ແລະບໍ່ມີ hidden source."),
  sp("FN-PLC-003", "WF-03-01", "Place/source/partner/campaign data available.", "currentTime server-side; latest verification per critical field.", ["Resolve source-linked label", "Calculate verification/freshness from checks", "Resolve active membership", "Resolve active sponsored campaign ແລະສົ່ງ labels ແຍກ"], "Missing evidence → unverified/stale, ບໍ່ assume verified.", "Combinations ຂອງ four labels ສະແດງອິດສະຫຼະ; paid state ບໍ່ຊື້ trust."),
  sp("FN-PLC-004", "WF-03-01", "Canonical Place contacts/coordinates loaded.", "target normalized; only published contact; device capability optional.", ["Create Map action ຖ້າ coordinates/map URL valid", "Create Call action ຈາກ primary valid phone", "Create Message actions ຈາກ enabled channels", "Attach web/copy fallback ແລະສົ່ງ available list"], "Invalid/missing target → omit action; no action → contact-unavailable state.", "ບໍ່ມີ action ທີ່ target ຫວ່າງ; deep link encode ຖືກ; fallback ຄົບ."),
  sp("FN-ACT-001", "WF-03-02", "Map action ສ້າງຈາກ FN-PLC-004.", "coordinates range valid; provider URL allowlist.", ["Choose native map URI by capability", "Encode coordinates/name", "Attempt launch", "Fallback web URL ແລະ emit intent event async"], "Native unavailable → web; both unavailable → copy coordinates.", "Expected coordinates ຖືກສົ່ງ; failure ບໍ່ຄ້າງ page; intent event ບໍ່ block."),
  sp("FN-ACT-002", "WF-03-02", "Phone action ມີ normalized number.", "phone valid for dialing; label unverified ຖ້າຈຳເປັນ.", ["Normalize/encode tel URI", "Attempt dialer", "Fallback display+copy number", "Emit Call intent async"], "No dialer → copy; invalid number → no launch.", "Dialer payload ກົງ contact; invalid input ບໍ່ຖືກເປີດ; retry dedupe intent."),
  sp("FN-ACT-003", "WF-03-02", "Messaging contact active.", "channel allowlist; target format/URL valid.", ["Select channel template", "Encode target ແລະ optional safe message", "Attempt native/web launch", "Fallback contact display ແລະ emit intent async"], "App absent → web/copy; unsupported channel → validation error.", "WhatsApp/Facebook target encode ຖືກ; raw script URL ຖືກປະຕິເສດ; event non-blocking."),
  sp("FN-ACT-004", "WF-03-02", "Browser/device storage available ຫຼື graceful fallback.", "placeId canonical; action save/unsave.", ["Read local saved set", "Add/remove canonical placeId", "Persist versioned payload", "Update UI ແລະ optional event"], "Storage denied/full → in-memory state + notice.", "Save repeated ບໍ່ຊ້ຳ; unsave absent ID safe; no server account/write."),
  sp("FN-ACT-005", "WF-03-02", "Canonical URL/metadata ready.", "URL origin/path trusted; title text escaped.", ["Build canonical share payload", "Use Web Share API ຖ້າມີ", "Fallback clipboard", "Return outcome ແລະ emit event async"], "Share cancelled → cancelled not error; clipboard denied → select/copy UI.", "Shared URL canonical ແລະບໍ່ແມ່ນ duplicate; cancellation ບໍ່ນັບ success."),

  sp("FN-SRC-001", "WF-04-01", "Admin authorized.", "URL/domain/platform valid; canonical URL unique; proposed Place optional valid.", ["Normalize URL/platform", "Find existing source by canonical URL", "Resolve/create Creator attribution", "Insert Proposed ContentSource + Audit in transaction"], "Duplicate URL → return existing; invalid domain → validation error.", "Create ຄັ້ງທຳອິດໄດ້ Proposed; retry ບໍ່ສ້າງຊ້ຳ; Audit ມີ actor."),
  sp("FN-SRC-002", "WF-04-01 / WF-10-02", "URL allowlisted; caller authorized/job claimed.", "Timeout/redirect limits; no private-network URL; result taxonomy fixed.", ["Resolve URL safely ໂດຍຈຳກັດ redirects", "Call permitted platform endpoint/embed", "Classify Available/TemporaryFailure/ConfirmedUnavailable", "Persist check result ແລະ next action ຫຼັງ external call"], "Timeout/5xx → Temporary; confirmed 404/private/removed → Confirmed per retry policy.", "SSRF targets rejected; transaction ບໍ່ຄ້າງຂະນະ call; classification ກົງ fixtures."),
  sp("FN-SRC-003", "WF-04-01", "FN-SRC-002 = Available.", "Read only permitted metadata fields/size; sanitize text/URLs.", ["Request official metadata/embed", "Allowlist creator/title/preview/reference fields", "Normalize Creator identity", "Persist metadata ບໍ່ລວມ media bytes"], "Metadata partial → store available fields + blocker; unsafe preview → omit.", "No binary video stored; creator/link preserved; unknown fields discarded."),
  sp("FN-SRC-004", "WF-04-01", "Admin authorized; Source Proposed/Checked; Place canonical.", "sourceId/placeId exist; Source not takedown; one Place per Source.", ["Resolve canonical Place", "Check current link/version", "Set content_source.place_id", "Write Audit with before/after"], "Place merged → use target; conflicting link → version conflict.", "Link points canonical ID; retry same pair safe; changing pair requires reason/Audit."),
  sp("FN-SRC-005", "WF-04-01", "Admin authorized; source record exists.", "Target transition allowed; publish gate URL+creator+place+available.", ["Load current source with lock/version", "Evaluate publish/unpublish gate", "Update lifecycle status/timestamp", "Write Audit in same transaction"], "Gate blocker → no change + blocker list; stale version → conflict.", "Only valid source Published; unpublish removes public read; audit failure rolls back."),
  sp("FN-SRC-006", "WF-04-02", "Source due/manual request; not Removed by takedown.", "Job claim unique; URL exists; attempt ID unique.", ["Claim source work", "Call FN-SRC-002 outside transaction", "Persist check history", "Update current availability, retry/recheck and public eligibility"], "Temporary → retry/fallback; Confirmed → hide feed; takedown → do not override.", "Concurrent workers produce one effective state; single timeout does not remove; confirmed failure does."),
  sp("FN-SRC-007", "WF-04-02", "Admin authorized; takedown request/source exist.", "Decision Approved/Rejected; reason required; request open.", ["On submission set public hold", "Load request/evidence/current source", "Approve → Removed/Takedown; Reject → restore prior eligible state", "Close request + Audit atomically"], "Stale/closed request → conflict; missing evidence → UnderReview/NeedsEvidence.", "Takedown hides immediately; approve/reject outcomes correct; retry decision does not duplicate."),

  sp("FN-PADM-001", "WF-05-01", "Admin authorized; reference data active.", "name/area/coordinates required; client request key; duplicate review acknowledged.", ["Normalize identity/location", "Call FN-PADM-008", "If unresolved duplicate stop", "Insert Place Draft + initial relations + Audit atomically"], "Candidate unresolved → duplicate-review-required; invalid coordinate → field error.", "Valid new Place creates one Draft; retry key returns same ID; duplicate path creates none."),
  sp("FN-PADM-002", "WF-05-01 / WF-06-01", "Admin authorized or approved correction context; Place not merged.", "Field code allowlist; value type; evidence/reason for critical field; expected version.", ["Resolve canonical Place", "Validate field-level permission/value", "Update owning entity (Place/contact/hour/price/category)", "Add Verification/Audit and increment version atomically"], "Stale version → conflict; unsupported field → validation error; merged → redirect-required.", "Only requested field changes; critical change has evidence; audit rollback protects consistency."),
  sp("FN-PADM-003", "WF-05-01", "Candidate Place/value supplied.", "Logical types, reference IDs, ranges, lifecycle-dependent requirements.", ["Validate identity/reference/location formats", "Validate child records and cross-field constraints", "Calculate completeness", "Return errors (block) and warnings (label) by field"], "Rule engine unavailable → fail closed for publish; draft may retain explicit invalid warning only if safe.", "Fixture errors map to exact fields; Unknown is not error when allowed; no data write."),
  sp("FN-PADM-004", "WF-05-01", "Place Draft/InReview exists.", "Current version; latest validation/source/duplicate/approval states.", ["Run FN-PADM-003", "Check valid Published-eligible Source", "Check no unresolved duplicate", "Check admin approval/evidence and return ready+blockers"], "Any dependency missing → ready=false; query failure → readiness unavailable.", "Each blocker independently tested; ready true only when all gates true; no state write."),
  sp("FN-PADM-005", "WF-05-01", "Admin authorized; Place Draft/InReview.", "approval reason; expected version; readiness true at commit time.", ["Lock/load Place", "Re-run FN-PADM-004", "Set Published/published_at/canonical slug", "Write Audit in same transaction"], "Blocker/stale version/slug conflict → rollback + explicit reason.", "Published only after gate; retry returns same state; Audit failure leaves non-published."),
  sp("FN-PADM-006", "WF-05-02", "Admin/quality authorized; Place Published/InReview.", "reason required; optionalUntil valid; expected version.", ["Resolve canonical Place", "Validate transition and active campaign impact", "Set Suspended + reason/until", "Audit atomically; trigger read-model invalidation"], "Already Suspended → current state; Archived/Merged → invalid transition.", "Suspended disappears from Feed/Search; history remains; campaign not active against it."),
  sp("FN-PADM-007", "WF-05-02", "Admin authorized; permanent closure evidence.", "reason/evidence/closedAt; expected version; no source-merge misuse.", ["Resolve/lock Place", "Validate permanent closure transition", "Set Archived + closed_at", "End/flag dependent campaign and Audit atomically"], "Evidence insufficient → suggest Suspend; merged source → invalid transition.", "Archived excluded publicly, not hard-deleted, and audit/evidence retained."),
  sp("FN-PADM-008", "WF-05-01 / WF-05-03", "Candidate identity has at least name plus one signal when possible.", "Normalize name/phone/coordinate/social; exclude same ID.", ["Find candidates by normalized phone/social exact match", "Find name/coordinate candidates", "Calculate per-signal score/explanation", "Deduplicate pair and sort; never merge automatically"], "Search unavailable → manual review blocker; insufficient signals → low-confidence list/none.", "Known duplicates rank high with signal explanation; distinct branches remain candidates only; no write except candidate record."),
  sp("FN-PADM-009", "WF-05-03", "Admin authorized; candidate reviewed; A≠B; target canonical.", "reason/evidence; versions of both Places; child conflict plan.", ["Lock both Places in canonical order and revalidate", "Reassign Sources/children/requests/campaigns/analytics", "Resolve unique child conflicts", "Create Redirect, mark source Merged/Archived and write correlated Audit atomically"], "Version/unique/conflict failure → rollback all; circular target → reject.", "After success no child references source; old slug redirects; injected failure at any step leaves original state."),
  sp("FN-PADM-010", "WF-03-01 / WF-05-03", "slug/placeId format valid.", "Redirect chain bounded; target cannot equal source; public policy applied.", ["Lookup current Place by slug/ID", "If merged lookup PlaceRedirect", "Follow bounded chain and detect cycle", "Return canonical Place/redirect/not-found"], "Cycle/too-deep → integrity error + alert; unknown → not-found.", "Current slug returns direct; merged slug returns canonical; cycle fixture fails safely."),

  sp("FN-REQ-001", "WF-06-01", "Canonical Place; requester contact; at least one change.", "Field allowlist; proposed value types; evidence refs safe; channel reference unique.", ["Resolve Place", "Create CorrectionRequest header", "Create one CorrectionItem per field + evidence refs", "Set received_at/SLA seed and Audit intake atomically"], "Duplicate channel ref → existing request; invalid field → item error/no partial create.", "Request/items count match input; values snapshot; retry does not duplicate; PII absent from analytics/log."),
  sp("FN-REQ-002", "WF-06-01", "Submitted request exists.", "Status Submitted/NeedsEvidence-resume; clock source server-side.", ["Check required requester/items/evidence", "Classify urgent fields", "Calculate acknowledge/decision SLA", "Set UnderReview or NeedsEvidence, priority and work item"], "Missing evidence → NeedsEvidence; invalid request → reject intake with reason.", "Urgent map/phone/closed gets priority; complete request due date correct; incomplete clock paused."),
  sp("FN-REQ-003", "WF-06-01", "Admin authorized; request open.", "missing-evidence list/message/channel; expected status/version.", ["Verify missing items", "Set NeedsEvidence + sla_paused_at", "Append outbound communication", "Commit then send external notice; record delivery result"], "Send failure → request remains NeedsEvidence + delivery work; stale status → conflict.", "SLA paused once; communication appended; external failure does not rollback correct state."),
  sp("FN-REQ-004", "WF-06-01", "Admin authorized; request UnderReview; approved item set non-empty.", "Each item pending; reason/evidence; Place version current.", ["Lock Request/Place", "Mark approved items and call FN-PADM-002", "Revalidate Place/readiness and derive header outcome", "Write Verification/Request/Audit atomically"], "Value conflict/gate safety issue → rollback or leave item pending with blocker; stale → conflict.", "Only approved items applied; partial decision details retained; injected audit failure rolls back all."),
  sp("FN-REQ-005", "WF-06-01", "Admin authorized; request/item open.", "Rejected item IDs; reason per item; expected version.", ["Lock request/items", "Mark selected items Rejected + reason/actor/time", "If all decided derive header Approved/Rejected", "Write Audit; queue notice after commit"], "Missing reason/closed item → validation/conflict.", "Public Place unchanged for rejected items; all-rejected header Rejected; retry safe."),
  sp("FN-REQ-006", "WF-06-01", "All items decided/actioned; requester outcome prepared.", "Final outcome consistent with items; request not already closed.", ["Recalculate final outcome", "Verify approved updates committed and notice recorded/queued", "Set Closed/closed_at", "Complete work item and Audit"], "Pending item/action → close-blocked; already closed → current outcome.", "Cannot close with pending item; closed_at set once; work item completed."),

  sp("FN-CMP-001", "WF-07-01", "Admin authorized; canonical Place exists.", "placement/label allowlist; start<end; price/reference format; request key.", ["Resolve canonical Place", "Normalize time/placement/agreement", "Insert Campaign Draft", "Write Audit atomically"], "Invalid period/place → field error; duplicate request → existing campaign.", "Draft has correct terms; no Place trust field changes; retry does not duplicate."),
  sp("FN-CMP-002", "WF-07-01", "Campaign exists.", "server currentTime; allowed source state; Place current status.", ["Check Place Published", "Check start/end and current transition context", "Check placement+label complete", "Return eligible + ordered blockers without state write"], "Missing Place/config → blocker; store error → unavailable.", "All blockers separately tested; paid status never affects verification; no write."),
  sp("FN-CMP-003", "WF-07-01", "Admin authorized; Campaign Draft.", "Expected version; FN-CMP-002 eligible.", ["Lock campaign", "Re-run eligibility", "Set Scheduled", "Write Audit atomically"], "Blocker/stale/already Ended → no change.", "Eligible Draft becomes Scheduled once; retry safe; audit rollback works."),
  sp("FN-CMP-004", "WF-07-01", "Authorized Admin or claimed Scheduler job.", "Allowed transition; reason for manual; server time; expected state.", ["Lock campaign", "Re-run eligibility for Activate/Resume", "Set Active/Paused/Ended timestamps", "Write Audit and invalidate placement atomically"], "Place non-public/expired/stale state → blocker; Ended cannot reactivate.", "Automatic boundaries correct; concurrent scheduler yields one transition; paused/ended absent from placement."),
  sp("FN-CMP-005", "WF-07-01", "Authorized reporter; campaign/period valid.", "Period within campaign/report range; metric definition version fixed.", ["Load campaign terms", "Aggregate impressions/place opens/unique intents", "Calculate rates and quality flags", "Return summary with definitions/disclaimer"], "Insufficient/missing data → flagged partial summary, not invented values.", "Counts match fixtures; intent never labeled visit/sale; no session rows exposed."),

  sp("FN-ADM-001", "WF-08-01", "Auth provider available; Admin record exists/invited.", "Credential handled by provider; auth_subject unique; status Active.", ["Verify proof with Auth Provider", "Resolve AdminUser by subject", "Check status/revocation", "Issue/accept bounded session context"], "Invalid proof → unauthenticated; inactive → forbidden; provider timeout → retryable.", "Valid active user authenticated; suspended denied; credentials never stored/logged."),
  sp("FN-ADM-002", "WF-08-01", "Authenticated Admin context.", "action/resource codes allowlisted; session not stale.", ["Load role/status", "Map action to permission", "Apply resource/state restrictions", "Return allow/deny + non-sensitive reason"], "Unknown action → deny; stale session/status → deny.", "FullAdmin allowed approved actions; inactive/unknown denied; deny causes no domain call."),
  sp("FN-ADM-003", "WF-08-01", "Admin authorized.", "queue type/status/priority/due filters; pageSize/cursor.", ["Resolve allowed queue types", "Query open operational entities/work items", "Order urgent then overdue then due", "Return summaries+cursor without protected payload"], "Invalid filter → field error; source entity missing → exclude+integrity signal.", "Ordering/cursor stable; PII/evidence hidden from list; no unbounded result."),
  sp("FN-ADM-004", "WF-08-01", "Privileged command authorized and domain transaction open.", "actor/entity/action/reason/correlation; snapshots sanitized/size-limited.", ["Validate required audit fields", "Redact secrets/protected text", "Append immutable AuditLog", "Return audit ID; let domain transaction commit"], "Insert failure → fail command/rollback; oversize snapshot → reject or approved truncation marker.", "Every privileged fixture has audit; secret fields absent; update/delete of audit disallowed."),

  sp("FN-ANA-001", "WF-09-01", "Privacy notice available.", "Choice EssentialOnly/AnalyticsAllowed; versioned preference.", ["Show/read choice", "Store device preference with policy version", "Apply choice immediately", "Optionally send non-identifying consent event if allowed"], "Storage unavailable → session-only Essential default/choice; no blocking.", "Reject choice preserves core journey and sends no optional event; preference changes take effect."),
  sp("FN-ANA-002", "WF-09-01", "Consent mode known.", "Existing session format/expiry; random ID cryptographically safe.", ["Read device session", "If valid reuse; else generate random ID", "Set started/last_seen/expires", "Persist minimal session according to consent"], "Storage denied → memory session; malformed ID → replace.", "No name/phone/email; expiry works; concurrent tabs follow documented session policy."),
  sp("FN-ANA-003", "WF-09-01", "Event endpoint available; consent/payload supplied.", "event ID unique; payload size; allowed origin/rate; FN-ANA-004 passes.", ["Authenticate public origin/rate context", "Call payload validator", "Insert AnalyticsEvent", "For action call FN-ANA-005 in same transaction; return minimal status"], "Invalid → rejected; duplicate event ID → existing accepted result; store overload → retryable.", "Retry same ID stores once; invalid PII field rejected; action and intent atomic."),
  sp("FN-ANA-004", "WF-09-01", "Event dictionary/version loaded.", "eventName/version/consent; ID existence; property allowlist/types.", ["Find event definition", "Check consent requirement", "Validate entity references and property schema", "Reject PII/unknown fields or return sanitized payload"], "Unknown/version mismatch/PII → validation error.", "All taxonomy fixtures accepted/rejected correctly; sanitized output has only allowlisted keys; no write."),
  sp("FN-ANA-005", "WF-09-01", "Valid Map/Call/Message event within event transaction.", "session/place/action/time; definition window/version.", ["Build dedupe bucket/key", "Attempt unique DecisionIntent insert", "On conflict mark non-unique repeat", "Return unique flag/key without exposing history"], "Store conflict means duplicate, not system error; invalid action → validation error.", "Rapid repeats yield one intent; different place/action/window yield separate intents; concurrency safe."),
  sp("FN-ANA-006", "WF-09-02", "Authorized report context; period/version valid.", "Time zone, filters, minimum cohort/quality rules.", ["Select event/intent snapshot", "Count distinct metrics per dictionary", "Calculate funnel rates with zero-denominator handling", "Attach definition/data-quality flags"], "Mixed definition/low quality → split or flagged result; query timeout → retryable.", "Known dataset produces exact counts/rates; division by zero safe; no session rows returned."),
  sp("FN-ANA-007", "WF-09-02", "Authorized Admin/partner scope; canonical placeId.", "Period/definition; caller limited to allowed Place; minimum privacy threshold.", ["Resolve canonical Place", "Aggregate reach/opens/intent by action", "Apply privacy/quality suppression", "Return summary + intent disclaimer"], "Unauthorized place → forbidden; insufficient data → suppressed/flagged.", "Partner sees only own aggregate; action totals reconcile; no individual session/PII."),

  sp("FN-DQ-001", "WF-10-01", "Scheduler lease; Place tiers/check dates available.", "currentDate server-side; batch size; active non-merged Place.", ["Claim scheduler batch", "Select checks with expires_at≤threshold", "Call FN-DQ-002", "Upsert unique open WorkItems with due/priority"], "Lease lost → stop; per-record failure → record attempt and continue bounded batch.", "30/60-day fixtures create correct work; rerun does not duplicate open item; archived excluded."),
  sp("FN-DQ-002", "WF-10-01", "Tier and latest field checks available.", "Partner=30, Free=60; critical field list/version; currentDate.", ["For each critical field find latest valid check", "Calculate dueDate from tier", "Classify Fresh/Due/Stale", "Aggregate worst status + stale field list"], "Missing check → Due/Stale per launch policy, never Fresh.", "Boundary dates tested; each field status visible; no data write; partner/free differ correctly."),
  sp("FN-DQ-003", "WF-10-01", "Authorized job/Admin; FN-DQ-002 reports stale/due.", "Canonical placeId; stale fields; expected version; open work uniqueness.", ["Lock/update Place quality status", "Set public review label when rule requires", "Upsert WorkItem", "Write Audit atomically"], "Stale version → retry recalculation; merged Place → target redirect.", "Stale label/work item consistent; rerun safe; status does not auto-delete Place."),
  sp("FN-DQ-004", "WF-10-01", "Admin authorized; claimed WorkItem; evidence present.", "Checked field allowlist; results/evidence; Place version.", ["Validate each field against current Place", "Append VerificationChecks with expires_at", "Recalculate quality status", "Complete/retain WorkItem and Audit atomically"], "Conflicting/unverified field → keep stale/needs review; stale version → conflict.", "Verification history appended, not overwritten; partial checks keep outstanding fields; audit rollback atomic."),
  sp("FN-DQ-005", "WF-10-02", "Scheduler/Admin; Source ConfirmedUnavailable and due; no takedown.", "Job claim/attempt ID; next_check_at; canonical URL.", ["Claim Source work", "Call FN-SRC-002 outside transaction", "Append availability check", "If available invoke restore gate; else schedule next action"], "Network timeout → Temporary result/retry; lease lost → no state overwrite.", "Due source checked once per attempt; takedown excluded; history and next action correct."),
  sp("FN-DQ-006", "WF-10-02", "Latest check Available; Source not takedown/removed.", "URL/creator/place link/publish eligibility; expected version.", ["Lock/load Source", "Revalidate attribution and canonical Place", "Set Checked/Published based on prior eligible state", "Complete work + Audit atomically"], "Missing attribution/link → blocker work item; state changed/takedown → abort.", "Valid source restored once; invalid not restored; takedown never auto-restored; audit atomic."),
];

const specById = new Map(specs.map((item) => [item.id, item]));
const missingSpecs = systemFunctionCatalog.filter((item) => !specById.has(item.id)).map((item) => item.id);
const unknownSpecs = specs.filter((item) => !systemFunctionCatalog.some((fn) => fn.id === item.id)).map((item) => item.id);
const duplicateSpecs = specs.filter((item, index) => specs.findIndex((candidate) => candidate.id === item.id) !== index).map((item) => item.id);
const moduleGroups = Array.from(new Set(systemFunctionCatalog.map((item) => item.moduleId)));
const totalAlgorithmSteps = specs.reduce((sum, item) => sum + item.algorithm.length, 0);

export default function SystemAnalysisFunctionSpecifications() {
  return (
    <section className={styles.saSpecifications} id="sa-function-specifications">
      <header className={styles.saPartHeader}>
        <span>ພາກ E · ຂັ້ນ 4 ຂອງ SA</span>
        <h2>Function Specification & Algorithm</h2>
        <p>ພາກນີ້ຂະຫຍາຍ 64 Logical Functions ຈາກ Function Catalog ໃຫ້ເປັນ Implementation Contract: Caller/Input/Output ຈາກພາກ B, Call Order ຈາກພາກ D ແລະສູດປະມວນຜົນລວມ {totalAlgorithmSteps} Algorithm Steps. ແຕ່ລະ Specification ມີ Preconditions, Validation, Data Operation, Failure behavior, Security, Performance, Observability ແລະ Testable Result.</p>
        <p>Algorithm ໃນ SA ເປັນ Technology-neutral pseudocode: ມັນລະບຸຜົນ ແລະລຳດັບທີ່ Code ຕ້ອງຮັກສາ ແຕ່ບໍ່ບັງຄັບ framework, class, endpoint path, SQL syntax ຫຼື library. Physical interface ຈະຖືກກຳນົດໃນ Technical Design.</p>
      </header>

      <div className={styles.saCatalogSummary}>
        <article><small>FUNCTION SPECS</small><strong>{specs.length}</strong><p>ກົງກັບ Function Catalog 1:1</p></article>
        <article><small>ALGORITHM STEPS</small><strong>{totalAlgorithmSteps}</strong><p>Technology-neutral processing sequence</p></article>
        <article><small>MODULES</small><strong>{moduleGroups.length}</strong><p>Security/Performance policy ແຍກຕາມ Module</p></article>
        <article><small>COVERAGE</small><strong>{missingSpecs.length + unknownSpecs.length + duplicateSpecs.length === 0 ? "100%" : "FAIL"}</strong><p>Missing/unknown/duplicate specification check</p></article>
      </div>

      <section className={styles.documentArticleSection}>
        <span>E1 · SPECIFICATION CONTRACT</span>
        <h2>ຫົວຂໍ້ບັງຄັບຂອງ Function Specification</h2>
        <div className={styles.saModelRules}>
          <article><b>CONTRACT</b><strong>Input → Output</strong><p>ຊື່/ຄວາມໝາຍຂອງ Input/Output ຕ້ອງກົງ Function Catalog ແລະຫ້າມຮັບ field ນອກ allowlist.</p></article>
          <article><b>GUARD</b><strong>Precondition</strong><p>ສິ່ງທີ່ຕ້ອງເປັນຈິງກ່ອນ Algorithm; ບໍ່ຜ່ານແລ້ວຫ້າມປ່ຽນ state.</p></article>
          <article><b>PROCESS</b><strong>Algorithm</strong><p>ລຳດັບ normalize → validate → read/decide/write → return; ບອກ transaction/external boundary ຜ່ານ Workflow.</p></article>
          <article><b>FAILURE</b><strong>No Guessing</strong><p>ກຳນົດຜົນເມື່ອ validation, dependency, conflict ຫຼື external call ລົ້ມ; Error Code ລະອຽດຢູ່ຂັ້ນ 5.</p></article>
          <article><b>CONTROL</b><strong>Security & Limit</strong><p>ກຳນົດ authorization, PII, URL safety, pagination, idempotency ແລະຂອບເຂດ performance.</p></article>
          <article><b>EVIDENCE</b><strong>Testable Result</strong><p>ປະໂຫຍກທີ່ Test Case ສາມາດພິສູດໄດ້ ໂດຍບໍ່ອີງຄຳວ່າ “ເຮັດວຽກຖືກ”.</p></article>
        </div>
      </section>

      <section className={styles.documentArticleSection}>
        <span>E2 · FUNCTION SPECIFICATION CATALOG</span>
        <h2>64 Specifications ແຍກຕາມ 10 Modules</h2>
        <div className={styles.saSpecModules}>
          {moduleGroups.map((moduleId) => {
            const functions = systemFunctionCatalog.filter((item) => item.moduleId === moduleId);
            const first = functions[0];
            const policy = modulePolicies[moduleId];
            return <section key={moduleId}>
              <header><span>{moduleId}</span><div><strong>{first.moduleName}</strong><small>{first.moduleLao}</small></div><em>{functions.length} Specs</em></header>
              <div className={styles.saSpecPolicy}><div><b>SECURITY BASELINE</b><p>{policy.security}</p></div><div><b>PERFORMANCE BASELINE</b><p>{policy.performance}</p></div><div><b>OBSERVABILITY</b><p>{policy.observability}</p></div></div>
              {functions.map((fn, index) => {
                const spec = specById.get(fn.id);
                if (!spec) return null;
                return <details key={fn.id} open={moduleId === "MOD-01" && index === 0}>
                  <summary><span>{fn.id}</span><div><strong>{fn.name}</strong><small>{fn.type} · Caller: {fn.caller}</small></div><em>{spec.algorithm.length} Steps</em></summary>
                  <div className={styles.saSpecContract}><div><b>INPUT CONTRACT</b><p>{fn.input}</p></div><div><b>OUTPUT CONTRACT</b><p>{fn.output}</p></div><div><b>WORKFLOW</b><p>{spec.workflow}</p></div></div>
                  <div className={styles.saSpecGuards}><div><b>PRECONDITIONS</b><p>{spec.preconditions}</p></div><div><b>VALIDATION</b><p>{spec.validation}</p></div></div>
                  <ol className={styles.saAlgorithm}>{spec.algorithm.map((step, stepIndex) => <li key={step}><b>{String(stepIndex + 1).padStart(2, "0")}</b><p>{step}</p></li>)}</ol>
                  <div className={styles.saSpecDetails}>
                    <div><b>DATA OPERATION</b><p>{fn.data}</p></div><div><b>BUSINESS RULE</b><p>{fn.rules}</p></div><div><b>FAILURE BEHAVIOR</b><p>{spec.failures}</p></div><div><b>SECURITY / PERFORMANCE</b><p>{policy.security} {policy.performance}</p></div><div><b>DEPENDENCIES</b><p>{fn.dependencies}</p></div><div><b>TESTABLE RESULT</b><p>{spec.test}</p></div>
                  </div>
                </details>;
              })}
            </section>;
          })}
        </div>
      </section>

      <section className={styles.documentArticleSection}>
        <span>E3 · ALGORITHM DESIGN RULES</span>
        <h2>ກົດຮ່ວມທີ່ Code Review ແລະ Test ຕ້ອງຮັກສາ</h2>
        <ol className={styles.reviewDecisions}>
          <li><b>01 · VALIDATE BEFORE WRITE</b><div><strong>ຫ້າມ partial mutation:</strong><p>Normalize ແລະ validate ທຸກ input/permission/current state ກ່ອນ write. ຖ້າມີ field ໜຶ່ງບໍ່ຜ່ານ ຕ້ອງບໍ່ commit ສ່ວນອື່ນ ນອກຈາກ Function ລະບຸ item-level decision ຊັດເຈນ.</p></div></li>
          <li><b>02 · SERVER AUTHORITY</b><div><strong>Time, role ແລະ state ຈາກ Server:</strong><p>Client ສາມາດສົ່ງ intent ແຕ່ current time, authorization, entity version, lifecycle status ແລະ eligibility ຕ້ອງກວດຈາກ Server ກ່ອນຕັດສິນ.</p></div></li>
          <li><b>03 · SAFE RETRY</b><div><strong>Command ບໍ່ສ້າງຊ້ຳ:</strong><p>Create/Event/Job ໃຊ້ request/event/attempt key; Update ໃຊ້ expected version; state transition ຊ້ຳສົ່ງ current result ຫຼື conflict ຕາມ contract.</p></div></li>
          <li><b>04 · FAIL CLOSED</b><div><strong>Trust/Publish/Permission:</strong><p>ຖ້າກວດສິດ, publish gate, evidence ຫຼື source safety ບໍ່ໄດ້ ໃຫ້ປະຕິເສດ/ຄົງ Draft ແລະບອກ blocker; ຫ້າມຄາດເດົາວ່າຜ່ານ.</p></div></li>
          <li><b>05 · EXTERNAL IS UNTRUSTED</b><div><strong>Timeout, allowlist, sanitize:</strong><p>URL/metadata/response ຈາກ platform ພາຍນອກຕ້ອງຈຳກັດ domain, redirect, size, time ແລະ field; network failure ບໍ່ຢູ່ໃນ long transaction.</p></div></li>
          <li><b>06 · EVIDENCE, NOT CLAIM</b><div><strong>Metrics ແລະ Trust:</strong><p>Algorithm ຫ້າມປ່ຽນ Decision Intent ເປັນ Visit/Sale, ຫ້າມປ່ຽນ paid membership/campaign ເປັນ Verification ແລະຫ້າມສ້າງ unknown data.</p></div></li>
        </ol>
      </section>

      <section className={styles.documentArticleSection}>
        <span>E4 · SPECIFICATION COVERAGE GATE</span>
        <h2>Function Catalog → Specification Coverage</h2>
        <div className={missingSpecs.length + unknownSpecs.length + duplicateSpecs.length === 0 ? styles.saCoveragePass : styles.saCoverageFail}>
          <strong>{specs.length}/{systemFunctionCatalog.length}</strong><div><b>{missingSpecs.length + unknownSpecs.length + duplicateSpecs.length === 0 ? "PASS — ONE SPEC PER FUNCTION" : "SPECIFICATION MISMATCH"}</b><p>{missingSpecs.length + unknownSpecs.length + duplicateSpecs.length === 0 ? "Function Catalog ທຸກອັນມີ Specification ໜຶ່ງອັນພອດີ; ບໍ່ຂາດ, ບໍ່ເກີນ ແລະບໍ່ຊ້ຳ ID." : `Missing: ${missingSpecs.join(", ") || "—"}; Unknown: ${unknownSpecs.join(", ") || "—"}; Duplicate: ${duplicateSpecs.join(", ") || "—"}`}</p></div>
        </div>
        <ul className={styles.decisionList}>
          <li><b>01</b><span>64 Function IDs ມີ Specification 1:1 ແລະອ້າງ Workflow.</span></li>
          <li><b>02</b><span>Specification ທຸກອັນມີ Input/Output, Preconditions, Validation, Algorithm, Data, Failure ແລະ Testable Result.</span></li>
          <li><b>03</b><span>Command/Background/Event algorithms ມີ retry/concurrency/transaction rule ຈາກ Workflow ແລະ Module policy.</span></li>
          <li><b>04</b><span>Public/External/Admin/Analytics functions ມີ security boundary ທີ່ກວດໄດ້.</span></li>
          <li><b>05</b><span>Algorithm ບໍ່ສ້າງ Booking/Payment/User/Creator ecosystem ນອກ MVP.</span></li>
          <li><b>06</b><span>Failure behavior ລະບຸ result ແລະ safe state; Error Code/State Matrix ຈະລົງລະອຽດໃນຂັ້ນ 5.</span></li>
        </ul>
      </section>

      <aside className={styles.saNextStep}>
        <small>ສະຖານະ SA</small><h2>ຂັ້ນ 1–4 ຈັດເຮັດແລ້ວ · ຂັ້ນ 5 ແມ່ນ State Transition & Error Handling</h2>
        <p>ຂັ້ນ 5 ຈະນຳ lifecycle entities ແລະ failure behavior ໃນພາກ E ມາສ້າງ State/Event/Guard/Next-state Matrix, Error Taxonomy, Error Code, Retryability, User Message, Logging/Alerting ແລະ Recovery/Compensation Contract.</p>
      </aside>
    </section>
  );
}
