import styles from "../documents.module.css";

const decisionCriteria = [
  ["TS-C01", "ຄວາມສອດຄ່ອງ", "ຕ້ອງຮອງຮັບ TEC-01 Modular Monolith, relational source of truth, queue/outbox, link-only media ແລະ server-enforced security."],
  ["TS-C02", "Founder-led delivery", "ຄົນຈຳນວນນ້ອຍຕ້ອງສາມາດພັດທະນາ, deploy, debug, backup ແລະອັບເກຣດໄດ້ໂດຍບໍ່ຕ້ອງມີ Platform Team."],
  ["TS-C03", "Pilot cost", "ຫຼຸດ fixed service ທີ່ຈ່າຍຊ້ຳຊ້ອນ; ແຕ່ບໍ່ໃຊ້ free tier ທີ່ data ໝົດອາຍຸ ຫຼືບໍ່ມີ backup ເປັນ production baseline."],
  ["TS-C04", "Lao/mobile performance", "Guest journey ຕ້ອງອ່ານພາສາລາວໄດ້ດີເທິງ Android/4G; Search ຕ້ອງທົດສອບກັບຄຳລາວຈິງ ບໍ່ແມ່ນຄາດເດົາຈາກພາສາອັງກິດ."],
  ["TS-C05", "Data portability", "Schema, migration, export ແລະ object key ຕ້ອງຍ້າຍ provider ໄດ້; vendor-specific feature ຕ້ອງຢູ່ຫຼັງ adapter."],
  ["TS-C06", "Operational evidence", "ທຸກທາງເລືອກຕ້ອງມີ official support status, region, backup/restore, monitoring, exit path ແລະຄ່າໃຊ້ຈ່າຍທີ່ກວດຄືນໄດ້."],
] as const;

const stackCatalog = [
  ["TS-01", "Language", "TypeScript 5.x", "Frontend, backend, worker ແລະ shared contract", "ຫຼຸດການແປ type ຂ້າມ layer; Founder ຄຸມ codebase ດຽວ", "Pin exact minor/patch ໃນ lockfile; tsc ຕ້ອງຜ່ານ CI"],
  ["TS-02", "Web/Application", "Next.js 16.x Active LTS + React 19", "Guest Web, Admin Web, server-rendered route ແລະ HTTP API", "SEO/public page, responsive UI ແລະ server code ຢູ່ໃນ framework ດຽວ", "ຫ້າມໃຫ້ browser ຂຽນ DB ໂດຍກົງ; privileged mutation ຜ່ານ server"],
  ["TS-03", "Runtime", "Node.js 24 LTS", "Application process, worker, script ແລະ migration", "ຢູ່ໃນ LTS window ແລະກົງກັບ Graphile Worker requirement", "Pin major 24; ອັບ patch ຫຼັງ CI/Staging"],
  ["TS-04", "Primary Database", "PostgreSQL 18", "Canonical Place, Source, Workflow, Access, Audit, Campaign, Finance ແລະ Analytics", "Transaction, constraint, relation, JSONB, index ແລະ extension ຄົບໃນ data store ດຽວ", "Managed paid plan; backup/restore ແລະ connection limit ທົບທວນໃນ TEC-06"],
  ["TS-05", "Data access", "Drizzle ORM + reviewed SQL migrations", "Typed query, schema declaration ແລະ versioned migration", "API ຄ້າຍ SQL, ສາມາດກວດ generated SQL ແລະບໍ່ປິດບັງ database constraint", "ຫ້າມ drizzle-kit push ໃສ່ Production; migration ຕ້ອງ review/backup/rollback plan"],
  ["TS-06", "Search", "PostgreSQL normalized fields + pg_trgm + indexes", "Keyword, category, area, price band, tag ແລະ fuzzy candidate retrieval", "ບໍ່ເພີ່ມ Search Server ໃນ Pilot; projection ສ້າງຄືນຈາກ DB ໄດ້", "ບໍ່ຮັບປະກັນ Lao relevance; TEC-05 ຕ້ອງ benchmark query set ຈິງ"],
  ["TS-07", "Background Job", "Graphile Worker + Transactional Outbox", "Source recheck, freshness, search projection, scheduled campaign, aggregate ແລະ notification", "ໃຊ້ PostgreSQL ເປັນ queue ເພື່ອຫຼຸດ Redis/service ເພີ່ມ; ມີ retry/backoff", "At-least-once: task ຕ້ອງ idempotent; dead job ຕ້ອງມີ alert/manual replay"],
  ["TS-08", "Object Storage", "Cloudflare R2 via S3-compatible API", "Approved Place images, poster, restricted evidence ແລະ export", "S3-compatible adapter ແລະ no-egress-charge baseline ຊ່ວຍຄວບຄຸມ media cost", "Social video ຍັງ link-only; bucket private by default; signed URL/retention ຢູ່ TEC-06"],
  ["TS-09", "Identity", "Managed OIDC provider + server session", "Admin sign-in, role claim, session expiry ແລະ step-up action", "ບໍ່ສ້າງ password/MFA system ເອງ ແລະປ່ຽນ provider ຜ່ານ OIDC adapter ໄດ້", "Provider ສຸດທ້າຍ, MFA, session/role mapping ຕັດສິນໃນ TEC-06"],
  ["TS-10", "Testing", "Vitest + Playwright", "Unit/domain, integration/DB, contract ແລະ E2E/accessibility journey", "TypeScript-friendly fast tests + real-browser test ຂ້າມ Chromium/Firefox/WebKit", "CI ຕ້ອງແຍກ unit/integration/E2E; manual accessibility ຍັງຈຳເປັນ"],
  ["TS-11", "Observability", "Structured JSON logs + OpenTelemetry traces/metrics", "Request/job correlation, latency, error, queue age ແລະ external dependency", "Open standard ຊ່ວຍປ່ຽນ backend; trace/metric ສະຖານະ stable ໃນ JavaScript", "ບໍ່ log secret/PII; logs pipeline ຈະລັອກໃນ TEC-06"],
  ["TS-12", "Delivery", "GitHub Actions + Docker/OCI image + Render Blueprint", "Lint, typecheck, test, build, migration gate, deploy ແລະ rollback", "Repository-to-environment ກວດສອບໄດ້; web/worker ໃຊ້ code/image baseline ດຽວ", "Production deploy ຕ້ອງຜ່ານ approval; migration ແຍກຈາກ app start"],
] as const;

const repositoryLayout = [
  ["apps/web", "Next.js Guest + Admin + Public/Admin API", "TS-02; ARC-C02—06"],
  ["apps/worker", "Graphile Worker task executors; ບໍ່ expose public URL", "TS-07; ARC-C09"],
  ["packages/domain", "Pure business rules, state transition, calculation ແລະ policy", "PRO-02 Functions/Algorithms"],
  ["packages/db", "Drizzle schema, SQL migration, repository ແລະ transaction helper", "TS-04/05; TEC-04"],
  ["packages/contracts", "Request/response/event schema ແລະ error code ຮ່ວມ", "TEC-04 API contract"],
  ["packages/integrations", "Social, map, object storage, identity ແລະ notification adapters", "ARC-C11—13"],
  ["packages/observability", "Logger, request/job ID, metrics/tracing bootstrap ແລະ redaction", "TS-11; TEC-06"],
  ["packages/test-fixtures", "Synthetic DATA-01—08, builders ແລະ deterministic seed", "PRO-04 test contract"],
] as const;

const hostingOptions = [
  ["HOST-A", "Render · Singapore", "Web Service + Background Worker + Managed PostgreSQL 18; private network; Blueprint", "Operational flow ງ່າຍ, Singapore ມີ app/database, paid Postgres ມີ continuous backup/PITR", "Worker ບໍ່ມີ free plan; region ປ່ຽນບໍ່ໄດ້ໂດຍກົງ; ລາຄາຕ້ອງ refresh", "Recommended for Pilot"],
  ["HOST-B", "Fly.io · Singapore", "Machines + Managed Postgres ຢູ່ SIN", "Control/placement ສູງ ແລະ Singapore ຮອງຮັບ Managed Postgres", "Operations, networking ແລະ capacity tuning ຫຼາຍກວ່າ; ນັບ founder ops time", "Fallback if Render constraint fails"],
  ["HOST-C", "Self-managed VPS", "Application, worker, PostgreSQL, backup ແລະ monitoring ຈັດການເອງ", "ຄວບຄຸມສູງ; invoice ອາດເບິ່ງຕ່ຳ", "Patch, hardening, backup test, failover, alert ແລະ incident ເປັນພາລະ founder", "Rejected for Pilot"],
] as const;

const environments = [
  ["Local", "Developer machine + containerized PostgreSQL", "Synthetic fixtures; mocked external adapters", "Fast feedback; no production credential/data"],
  ["CI", "Ephemeral app + PostgreSQL service", "Deterministic fixtures", "Lint, typecheck, unit, migration, integration, build; E2E on release candidate"],
  ["Pilot/Staging", "Render Singapore service group, non-public Admin test access", "Approved/anonymized pilot copy", "Production-like config, restore/performance/UAT rehearsal"],
  ["Production", "Render Singapore web + worker + paid PostgreSQL; R2 objects", "Authoritative data", "Manual approval, backup, alert, audit, rollback and cost alert enabled"],
] as const;

const searchContract = [
  ["1", "Normalize", "Store original Lao text; create Unicode-normalized/search form; map approved aliases from CON-01. ຫ້າມທຳລາຍ canonical display text."],
  ["2", "Filter", "Apply publish state, category, area, price band, open/contact availability and sponsored eligibility at database level."],
  ["3", "Candidate retrieval", "Exact/prefix match ກ່ອນ, ແລ້ວ trigram similarity ສຳລັບ typo/candidate; use GIN/GiST ຕາມ benchmark."],
  ["4", "Rank", "Intent match + exactness + completeness/freshness + bounded popularity; Sponsored ແຍກຊັດ ແລະບໍ່ຊື້ rating/trust."],
  ["5", "Measure", "TEC-05 ສ້າງ Lao query set, expected results, zero-result rate, nDCG/precision ແລະ latency; dedicated engine ເພີ່ມສະເພາະຜ່ານ trigger."],
] as const;

const qualityGates = [
  ["QG-01", "Source quality", "ESLint + TypeScript noEmit + formatting/check conventions", "ທຸກ Pull Request"],
  ["QG-02", "Domain correctness", "Vitest unit tests ສຳລັບ state, permission, publish, sponsored, finance formula ແລະ dedupe", "Critical rule 100%; risk-based remainder"],
  ["QG-03", "Data safety", "Fresh PostgreSQL migration up/down strategy, constraint test, transaction/outbox integration test", "ກ່ອນ merge migration"],
  ["QG-04", "User journey", "Playwright Guest/Admin Must journeys, keyboard, mobile viewport ແລະ failure fallback", "ກ່ອນ Pilot release"],
  ["QG-05", "Non-functional", "PRO-04 performance targets, dependency timeout, rate limit, backup/restore, security and manual accessibility", "ກ່ອນ Public Pilot"],
  ["QG-06", "Supply chain", "Lockfile, dependency audit, image scan, secret scan ແລະ reproducible production build", "PR + scheduled weekly"],
] as const;

const costItems = [
  ["Application", "Web service monthly price × instance count × active environments", "Provider price/quote + invoice", "Scale compute ເມື່ອ CPU/memory/latency evidence"],
  ["Worker", "Worker monthly price × instance count", "Provider price/quote + queue-age metric", "ເລີ່ມ 1 small worker; ບໍ່ເພີ່ມ Redis"],
  ["Database", "Compute plan + provisioned storage + backup/PITR/HA option", "Provider price/quote + storage/connection metrics", "Paid managed plan only for Production"],
  ["Object storage", "GB-month + Class A writes + Class B reads + retrieval/egress where applicable", "R2 official rate + monthly usage", "Store approved images/evidence; no social video copy"],
  ["Observability", "Ingested logs/traces/metrics + retention + alert channel", "Provider rate + sampled volume", "Essential signals first; sampling/redaction"],
  ["External API", "Request unit × provider rate", "Provider quote/invoice", "Quota, timeout, cache; manual fallback"],
  ["Operational labor", "Founder/specialist hours × reference rate", "Time log + incident/maintenance record", "Show shadow cost even when no cash is paid"],
] as const;

const risks = [
  ["TS-R01", "High", "PostgreSQL search ບໍ່ຈັດອັນດັບຄຳລາວໄດ້ດີ", "Build Lao benchmark before freeze; aliases/exact-first; dedicated engine only after TEC-05 trigger", "Search Lead"],
  ["TS-R02", "High", "Graphile Worker at-least-once ເຮັດ side effect ຊ້ຳ", "Idempotency key, unique effect record, bounded retry, dead-job alert and replay runbook", "Backend Lead"],
  ["TS-R03", "High", "Managed provider outage/lock-in", "Same-region private network, export/restore drill, OCI image, standard PostgreSQL/S3/OIDC adapters", "Tech Lead"],
  ["TS-R04", "High", "Free/cheap tier ຖືກນຳໃຊ້ໃນ Production ໂດຍບໍ່ມີ backup", "Environment policy blocks free DB in Production; restore evidence before launch", "Operations"],
  ["TS-R05", "Medium", "Dependency update ທຳລາຍ build ຫຼື security", "Lockfile, patch cadence, CI/Staging, rollback and LTS-major review every quarter", "Tech Lead"],
  ["TS-R06", "Medium", "Log/analytics ເກັບ PII ຫຼາຍເກີນ", "Event allowlist, redaction, consent, retention and access review in TEC-06/DEL-04", "Security + Data"],
  ["TS-R07", "Medium", "R2/identity/external API credential ຮົ່ວ", "Secret manager, scoped token, rotation, no browser secret and audit", "Security"],
] as const;

const reviews = [
  ["REV-01", "Application baseline", "ອະນຸມັດ TypeScript + Next.js 16 Active LTS + React 19 + Node.js 24 LTS ເປັນ application/runtime baseline ຫຼືບໍ່?", "ແນະນຳໃຫ້ອະນຸມັດ; pin exact patch ໃນ lockfile/container ແລະອັບຜ່ານ CI/Staging."],
  ["REV-02", "Data baseline", "ອະນຸມັດ PostgreSQL 18 + Drizzle + reviewed SQL migration ເປັນ source-of-truth stack ຫຼືບໍ່?", "ແນະນຳໃຫ້ອະນຸມັດ; database constraint ແລະ migration SQL ເປັນສິ່ງບັງຄັບ."],
  ["REV-03", "Search & jobs", "ອະນຸມັດ PostgreSQL pg_trgm search + Graphile Worker/outbox ສຳລັບ Pilot ແລະຍັງບໍ່ເພີ່ມ Elasticsearch/Meilisearch/Redis ຫຼືບໍ່?", "ແນະນຳໃຫ້ອະນຸມັດແບບມີເງື່ອນໄຂ: Lao relevance, query latency ແລະ queue age ຕ້ອງວັດໃນ TEC-05/Production Pilot."],
  ["REV-04", "Hosting", "ອະນຸມັດ Render Singapore ເປັນ Pilot hosting baseline, Fly.io Singapore ເປັນ fallback ແລະບໍ່ໃຊ້ self-managed VPS ຫຼືບໍ່?", "ແນະນຳໃຫ້ອະນຸມັດ direction; ລາຄາ/plan ສຸດທ້າຍຕ້ອງ refresh ແລະມີ quote ກ່ອນຜູກມັດລາຍຈ່າຍ."],
  ["REV-05", "Quality & boundary", "ອະນຸມັດ Vitest/Playwright/OpenTelemetry, managed OIDC/S3 adapter ແລະ no AI/LLM in MVP ຫຼືບໍ່?", "ແນະນຳໃຫ້ອະນຸມັດ; identity/security ລັອກໃນ TEC-06, API/schema ລັອກໃນ TEC-04 ແລະ AI ຕ້ອງຜ່ານ TEC-05 evidence."],
] as const;

export default function TechStackDocument({ basePath }: { basePath: string }) {
  return <article className={`${styles.detailBody} ${styles.formalDocument}`}>
    <header className={styles.formalDocumentHeader}>
      <p>TEC-03 · ARCHITECTURE &amp; ENGINEERING</p>
      <h1>Tech Stack</h1>
      <h2>ຊຸດເຕັກໂນໂລຊີສຳລັບສ້າງ Production MVP ໂດຍຫຼຸດພາລະ Server, ຮັກສາ Data Portability ແລະກຳນົດຈຸດທີ່ Developer ເລີ່ມໄດ້</h2>
      <div className={`${styles.formalStatus} ${styles.formalDraftStatus}`}>ສະບັບ 0.1 · ຮ່າງສຳລັບທົບທວນ · 28 ສິງຫາ 2026</div>
    </header>

    <section className={styles.formalSection} id="ts-control"><h2><span>1.</span> ຂໍ້ມູນຄວບຄຸມເອກະສານ</h2><div className={styles.formalTableWrap}><table className={styles.formalTable}><tbody>
      <tr><th>ລະຫັດ / ສະບັບ</th><td>TEC-03 / 0.1</td><th>ສະຖານະ</th><td>ຮ່າງສຳລັບທົບທວນ</td></tr>
      <tr><th>ເຈົ້າຂອງ</th><td>Solution Architect / Tech Lead</td><th>ຜູ້ອະນຸມັດ</th><td>Product Owner</td></tr>
      <tr><th>Baseline</th><td colSpan={3}>TEC-01 1.0 · TEC-02 1.0 · PRO-02 1.0 · PRO-03 1.0 · PRO-04 0.9 · UX-05 0.11.0</td></tr>
      <tr><th>ຂໍ້ມູນຕາມເວລາ</th><td colSpan={3}>Version, provider region, support status ແລະລາຄາ ກວດລ່າສຸດ 28 ສິງຫາ 2026; ຕ້ອງ refresh ກ່ອນ procurement/deploy.</td></tr>
      <tr><th>ເອກະສານຮັບຕໍ່</th><td colSpan={3}>TEC-04 Database &amp; API · TEC-05 Search &amp; AI · TEC-06 Security/Infrastructure · DEL-01 Development Plan</td></tr>
    </tbody></table></div><h3>1.1 ປະຫວັດ</h3><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>ສະບັບ</th><th>ວັນທີ</th><th>ລາຍລະອຽດ</th></tr></thead><tbody><tr><td>0.1</td><td>28 ສິງຫາ 2026</td><td>ຮ່າງ application/data/search/job/storage/identity/testing/observability stack, hosting comparison, cost model, risk, source register ແລະ 5 review decisions.</td></tr></tbody></table></div></section>

    <nav className={styles.formalToc} aria-label="ສາລະບານ TEC-03"><h2>ສາລະບານ</h2><ol>
      <li><a href="#ts-purpose">ຈຸດປະສົງ</a></li><li><a href="#ts-recommendation">ຂໍ້ສະເໜີຫຼັກ</a></li><li><a href="#ts-criteria">ເກນການເລືອກ</a></li><li><a href="#ts-catalog">Stack Catalog</a></li><li><a href="#ts-code">Code Structure</a></li><li><a href="#ts-search">Search &amp; Jobs</a></li><li><a href="#ts-hosting">Hosting</a></li><li><a href="#ts-cost">Cost Model</a></li><li><a href="#ts-quality">Quality &amp; Security</a></li><li><a href="#ts-lifecycle">Lifecycle &amp; Risk</a></li><li><a href="#ts-handoff">Handoff &amp; Artifacts</a></li><li><a href="#ts-sources">Official Sources</a></li><li><a href="#ts-review">5 ຂໍ້ທົບທວນ</a></li>
    </ol></nav>

    <section className={styles.formalSection} id="ts-purpose"><h2><span>2.</span> ຈຸດປະສົງ ແລະຂອບເຂດ</h2><p>TEC-03 ຕອບຄຳຖາມວ່າ Developer ຈະໃຊ້ພາສາ, framework, database, search, background job, storage, identity, test, monitoring ແລະ hosting ຫຍັງເພື່ອປ່ຽນ TEC-01/02 ເປັນ Production MVP. ທຸກການເລືອກຕ້ອງລະບຸບົດບາດ, ເຫດຜົນ, ຂໍ້ຈຳກັດ, ວິທີທົດສອບ ແລະທາງອອກເມື່ອຕ້ອງປ່ຽນ.</p><div className={styles.formalNote}><strong>ສິ່ງທີ່ TEC-03 ຍັງບໍ່ເຮັດ</strong><p>ບໍ່ກຳນົດ physical table/column ຫຼື endpoint payload ລະອຽດ (TEC-04), ranking/AI algorithm ສຸດທ້າຍ (TEC-05), role/retention/backup/incident configuration ສຸດທ້າຍ (TEC-06), sprint/team/date ແລະ production budget (DEL-01). ສະບັບ 0.1 ບໍ່ແມ່ນອຳນາດຊື້ service.</p></div></section>

    <section className={styles.formalSection} id="ts-recommendation"><h2><span>3.</span> ຂໍ້ສະເໜີຫຼັກ</h2><div className={styles.proposalExecutive}><article><b>APPLICATION CORE</b><h3>TypeScript Modular Monolith</h3><p>Next.js 16 + React 19 ເທິງ Node.js 24 LTS, repository ດຽວ, domain boundary ຊັດ ແລະ web/worker ແຍກ process ແຕ່ໃຊ້ contract ຮ່ວມ.</p></article><article><b>MANAGED DATA PLANE</b><h3>PostgreSQL-first Pilot</h3><p>PostgreSQL 18 ເປັນ source of truth, search projection ແລະ job queue; Render Singapore ເປັນ hosting baseline, R2 ເກັບ object ແລະ OIDC ຈັດການ identity.</p></article></div><div className={styles.formalDecision}><strong>Decision intent</strong><p>ຈຸດໝາຍບໍ່ແມ່ນເລືອກ tool ຈຳນວນຫຼາຍ. ຈຸດໝາຍແມ່ນໃຫ້ Founder-led team ສ້າງ, ກວດ, deploy, ສຳຮອງ ແລະແກ້ incident ໄດ້ດ້ວຍຈຳນວນ service ຕ່ຳສຸດ ໂດຍຍັງບໍ່ຫຼຸດ data/security control.</p></div></section>

    <section className={styles.formalSection} id="ts-criteria"><h2><span>4.</span> ເກນການເລືອກ</h2><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>ID</th><th>ເກນ</th><th>ຄຳອະທິບາຍ</th></tr></thead><tbody>{decisionCriteria.map(([id,name,detail])=><tr key={id}><td><code>{id}</code></td><td><strong>{name}</strong></td><td>{detail}</td></tr>)}</tbody></table></div></section>

    <section className={styles.formalSection} id="ts-catalog"><h2><span>5.</span> Technology Stack Catalog</h2><p>Version ໃນຕາຕະລາງແມ່ນ major baseline. Exact version ຕ້ອງຢູ່ໃນ lockfile/container ແລະ Software Bill of Materials; ຫ້າມ deploy ໂດຍໃຊ້ tag <code>latest</code>.</p><div className={styles.formalTableWrap}><table className={`${styles.formalTable} ${styles.formalCatalogTable}`}><thead><tr><th>ID</th><th>Layer</th><th>Choice</th><th>ບົດບາດ</th><th>ເຫດຜົນ</th><th>Guardrail</th></tr></thead><tbody>{stackCatalog.map(([id,layer,choice,role,why,guardrail])=><tr key={id}><td><code>{id}</code></td><td><strong>{layer}</strong></td><td>{choice}</td><td>{role}</td><td>{why}</td><td>{guardrail}</td></tr>)}</tbody></table></div><div className={styles.formalDraftNotice}><strong>No AI/LLM in MVP baseline</strong><p>AI ບໍ່ແມ່ນ dependency ສຳລັບ Feed, Search, Place, Admin ຫຼື Decision Intent. Rule-based/search baseline ຕ້ອງຜ່ານກ່ອນ; TEC-05 ຈຶ່ງສາມາດສະເໜີ AI ພ້ອມ quality, privacy, latency ແລະ cost evidence.</p></div></section>

    <section className={styles.formalSection} id="ts-code"><h2><span>6.</span> Repository ແລະ Code Boundary</h2><p>ແນະນຳ pnpm workspace ໃນ repository ດຽວ. ບໍ່ຈຳເປັນເພີ່ມ monorepo orchestration platform ໃນ Pilot ຈົນກວ່າ build time ຫຼື team ownership ມີບັນຫາຈິງ.</p><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>Path</th><th>ຄວາມຮັບຜິດຊອບ</th><th>Trace</th></tr></thead><tbody>{repositoryLayout.map(([path,responsibility,trace])=><tr key={path}><td><code>{path}</code></td><td>{responsibility}</td><td>{trace}</td></tr>)}</tbody></table></div><h3>6.1 Dependency rule</h3><p><code>web/worker → contracts/domain → db/integrations</code>. Domain rule ບໍ່ import UI, provider SDK ຫຼື HTTP framework. Integration ແລະ storage ຕ້ອງຜ່ານ interface; ຈຶ່ງສາມາດ test ແລະປ່ຽນ provider ໂດຍບໍ່ປ່ຽນ business rule.</p></section>

    <section className={styles.formalSection} id="ts-search"><h2><span>7.</span> Search, Background Job ແລະ Data Consistency</h2><h3>7.1 Lao Search Baseline</h3><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>ລຳດັບ</th><th>ຂັ້ນ</th><th>ກົດການເຮັດວຽກ</th></tr></thead><tbody>{searchContract.map(row=><tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div><h3>7.2 Job/Outbox Contract</h3><ol className={styles.formalNumberList}><li>Admin command ກວດ permission, state, version ແລະ validation.</li><li>Business write + audit + outbox event commit ໃນ PostgreSQL transaction ດຽວ.</li><li>Dispatcher ປ່ຽນ outbox event ເປັນ Graphile Worker job ໂດຍມີ idempotency key.</li><li>Worker ດຳເນີນ task, update projection ຫຼື external adapter ແລະບັນທຶກ outcome.</li><li>Failure ລອງໃໝ່ແບບຈຳກັດ; ເກີນຈຳນວນທີ່ກຳນົດເຂົ້າ dead-job operational queue.</li></ol><div className={styles.formalNote}><strong>Consistency boundary</strong><p>Canonical data/audit/outbox ຕ້ອງ strong consistency. Search, notification, analytics aggregate ເປັນ eventual consistency ໄດ້ ແຕ່ຕ້ອງມີ status/updated-at/rebuild path.</p></div></section>

    <section className={styles.formalSection} id="ts-hosting"><h2><span>8.</span> Hosting, Environment ແລະ Deployment</h2><div className={styles.formalTableWrap}><table className={`${styles.formalTable} ${styles.formalCatalogTable}`}><thead><tr><th>ID</th><th>Option</th><th>Topology</th><th>ຂໍ້ດີ</th><th>ຂໍ້ຈຳກັດ</th><th>ຜົນສະເໜີ</th></tr></thead><tbody>{hostingOptions.map(([id,name,topology,benefit,limit,result])=><tr key={id}><td><code>{id}</code></td><td><strong>{name}</strong></td><td>{topology}</td><td>{benefit}</td><td>{limit}</td><td><strong>{result}</strong></td></tr>)}</tbody></table></div><h3>8.1 Environment Contract</h3><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>Environment</th><th>Runtime</th><th>Data</th><th>Control</th></tr></thead><tbody>{environments.map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={`${index}-${cell}`}>{index===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></div><div className={styles.formalDecision}><strong>Pilot production topology</strong><p>Internet → Render Web Service (Guest/Admin/API) → same-region private PostgreSQL; Render Background Worker → same PostgreSQL; Application/Worker → private R2 bucket/OIDC/external adapters. Database ບໍ່ເປີດ public ເກີນຄວາມຈຳເປັນ.</p></div></section>

    <section className={styles.formalSection} id="ts-cost"><h2><span>9.</span> Monthly Run Cost ແລະ Evidence</h2><p>TEC-03 ບໍ່ລະບຸ total ກີບແບບຄາດເດົາ ເພາະ compute plan, storage, traffic, exchange rate ແລະ provider price ປ່ຽນໄດ້. CSV ທີ່ແນບບັງຄັບໃຫ້ຕື່ມ official price/quote, currency/date ແລະ invoice ກ່ອນອະນຸມັດ production budget.</p><div className={styles.proposalFormula}><b>MONTHLY RUN COST</b><p>Application + Worker + Database + Object Storage + Observability + External API + Backup/Support Reserve</p><span>ຕ້ອງສະແດງທັງ Cash Cost ແລະ Founder Operational Labor; ບໍ່ນັບ free tier ເປັນ production saving ຖ້າຂາດ backup, uptime ຫຼື data durability.</span></div><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>Cost item</th><th>ສູດ</th><th>ຫຼັກຖານ</th><th>Control</th></tr></thead><tbody>{costItems.map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={`${index}-${cell}`}>{index===0?<strong>{cell}</strong>:cell}</td>)}</tr>)}</tbody></table></div><h3>9.1 ສະຖານະລາຄາ</h3><ul className={styles.formalNumberList}><li><strong>Cloudflare R2:</strong> official baseline ວັນທີກວດລະບຸ Standard storage USD 0.015/GB-month, Class A USD 4.50/ລ້ານ, Class B USD 0.36/ລ້ານ ແລະ direct egress free; ກວດຄືນກ່ອນຊື້.</li><li><strong>Render:</strong> ໃຊ້ current plan/quote ຈາກ dashboard ໃນວັນ procurement. Free PostgreSQL ໝົດອາຍຸ 30 ມື້ ແລະບໍ່ມີ backup, ຈຶ່ງຫ້າມໃຊ້ກັບ Production.</li><li><strong>FX:</strong> ປ່ຽນ USD → LAK ດ້ວຍອັດຕາຈາກຫຼັກຖານໃນວັນອະນຸມັດ; ບັນທຶກ date/source ໃນ CSV.</li></ul></section>

    <section className={styles.formalSection} id="ts-quality"><h2><span>10.</span> Quality, Security ແລະ Observability Baseline</h2><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>ID</th><th>Gate</th><th>ຫຼັກຖານ</th><th>ເວລາບັງຄັບ</th></tr></thead><tbody>{qualityGates.map(([id,name,evidence,when])=><tr key={id}><td><code>{id}</code></td><td><strong>{name}</strong></td><td>{evidence}</td><td>{when}</td></tr>)}</tbody></table></div><h3>10.1 Minimum security boundaries</h3><ul className={styles.formalNumberList}><li>Admin ໃຊ້ managed OIDC; no shared account; server ກວດ role/action/record ທຸກ mutation.</li><li>Secret ຢູ່ provider secret store, ບໍ່ຢູ່ source code/browser/log/export.</li><li>Business write + audit + outbox ຕ້ອງ atomic; audit failure ເຮັດໃຫ້ privileged mutation rollback.</li><li>R2 bucket/evidence private by default; signed access ແລະ retention ກຳນົດໃນ TEC-06.</li><li>Structured log ມີ request/job ID, outcome, safe error code ແລະ duration; redaction ກ່ອນ export.</li></ul></section>

    <section className={styles.formalSection} id="ts-lifecycle"><h2><span>11.</span> Version Lifecycle, Change Trigger ແລະ Risk</h2><h3>11.1 Version policy</h3><ol className={styles.formalNumberList}><li>Major runtime/framework/database ໃຊ້ LTS/supported line ແລະບັນທຶກ End-of-Support date.</li><li>Patch/security update: review ທຸກເດືອນ, CI/Staging ກ່ອນ Production.</li><li>Major update: Architecture Decision, migration/rollback, compatibility test ແລະ maintenance window.</li><li>Quarterly refresh: official version status, provider region/price, dependency vulnerability ແລະ cost threshold.</li></ol><h3>11.2 Risk Register</h3><div className={styles.formalTableWrap}><table className={`${styles.formalTable} ${styles.formalCatalogTable}`}><thead><tr><th>ID</th><th>Level</th><th>Risk</th><th>Control</th><th>Owner</th></tr></thead><tbody>{risks.map(([id,level,risk,control,owner])=><tr key={id}><td><code>{id}</code></td><td><strong>{level}</strong></td><td>{risk}</td><td>{control}</td><td>{owner}</td></tr>)}</tbody></table></div><h3>11.3 Trigger ທີ່ອະນຸຍາດໃຫ້ປ່ຽນ Stack</h3><p>Dedicated search/queue/cache ຫຼື service split ສາມາດເພີ່ມໄດ້ເມື່ອ 2 release windows ຕິດຕໍ່ກັນພົບ SLO/latency/queue backlog/cost/team-ownership bottleneck ທີ່ index, query, caching, worker capacity ຫຼື code boundary ແກ້ບໍ່ໄດ້. Change Decision ຕ້ອງລະບຸຜົນກ່ອນ-ຫຼັງ, cost ແລະ rollback.</p></section>

    <section className={styles.formalSection} id="ts-handoff"><h2><span>12.</span> Technical Handoff ແລະໄຟລ໌ນຳໃຊ້</h2><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>ເອກະສານ</th><th>ຮັບຈາກ TEC-03</th><th>ຍັງຕ້ອງຕັດສິນ</th></tr></thead><tbody><tr><td><strong>TEC-04</strong></td><td>PostgreSQL 18, Drizzle/SQL migration, repository/data boundary, outbox/search projection</td><td>Physical schema, index, API payload, version/error contract</td></tr><tr><td><strong>TEC-05</strong></td><td>PostgreSQL exact/prefix/trigram candidate baseline; no AI dependency</td><td>Lao benchmark, ranking weights, engine/AI escalation trigger</td></tr><tr><td><strong>TEC-06</strong></td><td>Render/R2/OIDC/OpenTelemetry direction, private boundaries</td><td>Provider plan, role/MFA, retention, backup/RPO/RTO, alert/incident</td></tr><tr><td><strong>DEL-01</strong></td><td>Workspace/dependency order, CI gates, environment and cost formula</td><td>Team capacity, sprint/calendar, quote and production budget</td></tr></tbody></table></div><h3 id="artifacts">12.1 ໄຟລ໌ນຳໃຊ້</h3><div className={styles.architectureArtifacts}><a href={`${basePath}/artifact-preview?file=tec03-tech-stack-baseline-2026-08-28.json&from=tech-stack`}><b>ພຣີວິວ Tech Stack JSON</b><span>Layer, choice, version policy, boundary, decision ແລະ source</span></a><a href={`${basePath}/artifact-preview?file=tec03-provider-cost-comparison-2026-08-28.csv&from=tech-stack`}><b>ພຣີວິວ Provider/Cost CSV</b><span>ຕື່ມ plan, quote, FX, monthly total ແລະ evidence</span></a><a href={`${basePath}/templates/tec03-tech-stack-baseline-2026-08-28.json`} download><b>ດາວໂຫຼດ JSON</b><span>Machine-readable handoff ສຳລັບ TEC-04—06</span></a><a href={`${basePath}/templates/tec03-provider-cost-comparison-2026-08-28.csv`} download><b>ດາວໂຫຼດ CSV</b><span>Planning template; ບໍ່ແມ່ນ approved purchase</span></a></div><div className={styles.formalDraftNotice}><strong>Definition of done for TEC-03 1.0</strong><p>REV-01—05 ຖືກຕັດສິນ; exact baseline/version policy ຖືກລັອກ; hosting/provider plan ມີ current official evidence/quote; Lao search spike ແລະ migration/worker spike ຜ່ານ; cost worksheet ມີ owner/date/source; ແລະ TEC-04/05/06/DEL-01 ບໍ່ຕ້ອງຄາດເດົາ stack boundary.</p></div></section>

    <section className={styles.formalSection} id="ts-sources"><h2><span>13.</span> Official Source Register</h2><p>ລິ້ງຕໍ່ໄປນີ້ຖືກກວດໃນວັນທີ 28 ສິງຫາ 2026. ສະຖານະ support, region ແລະລາຄາສາມາດປ່ຽນໄດ້.</p><ul className={styles.formalNumberList}><li><a href="https://nextjs.org/support-policy">Next.js Support Policy</a> — 16.x Active LTS.</li><li><a href="https://nodejs.org/en/about/previous-releases">Node.js Releases</a> — Node.js 24 Active LTS.</li><li><a href="https://www.postgresql.org/support/versioning/">PostgreSQL Versioning</a> ແລະ <a href="https://www.postgresql.org/docs/current/pgtrgm.html">pg_trgm</a>.</li><li><a href="https://orm.drizzle.team/docs/migrations">Drizzle Migrations</a> — versioned SQL migration options.</li><li><a href="https://worker.graphile.org/docs">Graphile Worker</a> — PostgreSQL-backed Node.js jobs, retry ແລະ at-least-once behavior.</li><li><a href="https://render.com/docs/regions">Render Regions</a>, <a href="https://render.com/docs/background-workers">Background Workers</a>, <a href="https://render.com/docs/postgresql-upgrading">PostgreSQL support</a> ແລະ <a href="https://render.com/docs/free">Free-tier limits</a>.</li><li><a href="https://fly.io/docs/reference/regions/">Fly.io Regions</a> — Singapore application/Managed Postgres availability.</li><li><a href="https://developers.cloudflare.com/r2/get-started/s3/">Cloudflare R2 S3 API</a> ແລະ <a href="https://developers.cloudflare.com/r2/pricing/">R2 Pricing</a>.</li><li><a href="https://playwright.dev/docs/languages">Playwright</a>, <a href="https://vitest.dev/guide/">Vitest</a> ແລະ <a href="https://opentelemetry.io/docs/languages/js/">OpenTelemetry JavaScript</a>.</li></ul></section>

    <section className={styles.formalSection} id="ts-review"><h2><span>14.</span> 5 ຂໍ້ທີ່ຕ້ອງທົບທວນກ່ອນ 1.0</h2><p>ສະບັບ 0.1 ຍັງບໍ່ອະນຸມັດ stack ຫຼືການຊື້ service. ກະລຸນາຕັດສິນ REV-01—05; ຖ້າປ່ຽນຂໍ້ໃດ ຈະປັບ catalog, cost, risk ແລະ handoff ໃຫ້ກົງກັນ.</p><div className={styles.formalTableWrap}><table className={styles.formalTable}><thead><tr><th>ID</th><th>ຫົວຂໍ້</th><th>ຄຳຖາມ</th><th>ຄຳແນະນຳ</th><th>ສະຖານະ</th></tr></thead><tbody>{reviews.map(([id,title,question,recommendation])=><tr key={id}><td><code>{id}</code></td><td><strong>{title}</strong></td><td>{question}</td><td>{recommendation}</td><td><strong>ລໍທົບທວນ</strong></td></tr>)}</tbody></table></div></section>

    <nav className={styles.docPagination} aria-label="ເອກະສານກ່ອນໜ້າ ແລະຕໍ່ໄປ"><a href={`${basePath}/documents/technical-proposal`}><small>← APPROVED PROPOSAL</small><strong>TEC-02 1.0</strong></a><a href={`${basePath}/documents/data-api`}><small>ຫຼັງ TEC-03 ອະນຸມັດ →</small><strong>TEC-04 Database &amp; API</strong></a></nav>
  </article>;
}
