export type DocumentStatus = "approved" | "in_progress" | "draft" | "next" | "planned";

export type ProjectDocument = {
  slug: string;
  code: string;
  title: string;
  english: string;
  category: string;
  summary: string;
  status: DocumentStatus;
  sections: string[];
};

export const categories = [
  { id: "business", no: "01", title: "Business & Finance", lao: "ທຸລະກິດ ແລະ ການເງິນ", description: "ກຳນົດເຫດຜົນທາງທຸລະກິດ, ຄວາມເປັນໄປໄດ້, ແຫຼ່ງທຶນ ແລະຕົວຊີ້ວັດ." },
  { id: "product", no: "02", title: "Product & Analysis", lao: "ຜະລິດຕະພັນ ແລະ ການວິເຄາະ", description: "ລະບຸຂອບເຂດ MVP, ຜູ້ໃຊ້, requirement ແລະກົດການເຮັດວຽກ." },
  { id: "content", no: "03", title: "Content & Trust", lao: "ເນື້ອຫາ ແລະ ຄວາມໜ້າເຊື່ອຖື", description: "ສ້າງມາດຕະຖານ content, place data, creator, verification ແລະສິດທິ." },
  { id: "design", no: "04", title: "UX/UI Design", lao: "ປະສົບການ ແລະ ໜ້າຕາລະບົບ", description: "ປ່ຽນ requirement ໃຫ້ເປັນ user flow, wireframe, prototype ແລະ design system." },
  { id: "technical", no: "05", title: "Architecture & Engineering", lao: "ໂຄງສ້າງ ແລະ ວິສະວະກຳ", description: "ກຳນົດ architecture, stack, data, API, security ແລະ infrastructure." },
  { id: "delivery", no: "06", title: "Delivery & Operations", lao: "ການພັດທະນາ ແລະ ດຳເນີນງານ", description: "ວາງແຜນສ້າງ, ທົດສອບ, release, monitoring ແລະບໍລິຫານຫຼັງ launch." },
] as const;

export const documents: ProjectDocument[] = [
  { slug: "product-vision", code: "BUS-01", title: "ວິໄສທັດຜະລິດຕະພັນ", english: "Product Vision", category: "business", summary: "ກຳນົດບັນຫາ, ກຸ່ມເປົ້າໝາຍ, ຄຸນຄ່າຫຼັກ ແລະຂອບເຂດທີ່ platform ຈະບໍ່ເຮັດ.", status: "approved", sections: ["Problem & target user", "Value proposition", "Product principles", "In scope / out of scope"] },
  { slug: "market-competitor", code: "BUS-02", title: "ຕະຫຼາດ ແລະ ຄູ່ແຂ່ງ", english: "Market & Competitor Analysis", category: "business", summary: "Pre-Pilot baseline ທີ່ວິເຄາະພຶດຕິກຳຜູ້ໃຊ້, ຄູ່ແຂ່ງລາຍຊື່ຈິງ, ຂະໜາດຕະຫຼາດເບື້ອງຕົ້ນ ແລະ Evidence Plan.", status: "approved", sections: ["User behavior", "Named competitors", "Market baseline", "Evidence plan"] },
  { slug: "business-canvas", code: "BUS-03", title: "ແຜນພາບທຸລະກິດ", english: "Business Model Canvas", category: "business", summary: "ສະຫຼຸບ customer segment, value, channel, partner, cost ແລະ revenue ໄວ້ໃນໜ້າດຽວ.", status: "approved", sections: ["Customer segments", "Value and channels", "Key activities and partners", "Cost and revenue"] },
  { slug: "feasibility-study", code: "BUS-04", title: "ການສຶກສາຄວາມເປັນໄປໄດ້", english: "Feasibility Study", category: "business", summary: "ປະເມີນຄວາມເປັນໄປໄດ້ດ້ານຕະຫຼາດ, content, ເຕັກນິກ, ການເງິນ ແລະກົດໝາຍ.", status: "approved", sections: ["Market feasibility", "Operational feasibility", "Technical feasibility", "Go / no-go criteria"] },
  { slug: "financial-structure", code: "BUS-05", title: "ໂຄງສ້າງການເງິນ", english: "Financial Structure (FS)", category: "business", summary: "ກຳນົດທຶນເລີ່ມຕົ້ນ, ລາຍຈ່າຍ, cash flow, runway, break-even ແລະແຜນລະດົມທຶນ.", status: "approved", sections: ["Capital structure", "Cost and cash flow", "Revenue scenarios", "Runway and break-even"] },
  { slug: "revenue-kpi", code: "BUS-06", title: "ລາຍຮັບ ແລະ ຕົວຊີ້ວັດ", english: "Revenue Model & KPI", category: "business", summary: "ຜູກຮູບແບບລາຍຮັບກັບ metric ທີ່ພິສູດວ່າ platform ພາຄົນໄປສູ່ການຕັດສິນໃຈ.", status: "approved", sections: ["Revenue streams", "North-star metric", "Funnel metrics", "Reporting cadence"] },

  { slug: "prd", code: "PRO-01", title: "ຂໍ້ກຳນົດຜະລິດຕະພັນ", english: "Product Requirements Document", category: "product", summary: "ແປ product vision ໃຫ້ເປັນ feature, user story, priority ແລະຜົນທີ່ວັດແທກໄດ້.", status: "approved", sections: ["Goals and users", "MVP feature scope", "User stories", "Success and acceptance"] },
  { slug: "system-analysis", code: "PRO-02", title: "ການວິເຄາະລະບົບ", english: "System Analysis (SA)", category: "product", summary: "ສະບັບ 1.0 ອະນຸມັດແລ້ວ: 7 ຂັ້ນຂອງ SA ເຊື່ອມ 13 Requirements ຫາ 64 Functions, 27 Entities, 16 Workflows, 7 State Machines, 30 Error Codes ແລະ 9 Work Packages ສຳລັບ Developer Handoff.", status: "approved", sections: ["System context and rules", "Function, data, workflow and algorithm", "State, error and traceability", "Development starting point and dependency order"] },
  { slug: "mvp-scope", code: "PRO-03", title: "ຂອບເຂດ MVP", english: "MVP Scope & Prioritization", category: "product", summary: "ສະບັບ 1.0 ອະນຸມັດແລ້ວ: ກຳນົດສິ່ງທີ່ຈະສ້າງ ແລະຍັງບໍ່ສ້າງ, Pilot 30 → 60 → 100 Places, Social Source, Revenue/Manual Operation Scope ແລະຫຼັກຖານທີ່ຕ້ອງຜ່ານກ່ອນ Public MVP.", status: "approved", sections: ["Purpose and first-version overview", "User journey and build scope", "Deferred features and development order", "Detailed priority catalog and release gates"] },
  { slug: "requirements-acceptance", code: "PRO-04", title: "Requirement ແລະ ເກນຮັບມອບ", english: "Requirements & Acceptance Criteria", category: "product", summary: "ສະບັບ 0.9 ອະນຸມັດ Acceptance Authority, Test Environment/Data, Defect Policy, 4 Pilot Performance Targets, 7 UAT Journeys ແລະ Evidence Contract; ລໍ Consent/Retention Baseline ກ່ອນ 1.0.", status: "in_progress", sections: ["Requirement and acceptance language", "13 requirements and 46 acceptance criteria", "Test levels, data and evidence", "Pass policy and traceability coverage"] },

  { slug: "content-taxonomy", code: "CON-01", title: "ມາດຕະຖານການຈັດໝວດ", english: "Content Taxonomy", category: "content", summary: "ສະບັບ 0.9 ມີ Canonical Term Registry ແລະ Price Measurement Contract; ລໍຊື່ເຂດ Pilot ແລະຊ່ວງຈຳນວນກີບຂອງ ₭/₭₭/₭₭₭ ກ່ອນ 1.0.", status: "in_progress", sections: ["Taxonomy hierarchy and filters", "Search vocabulary", "Canonical term registry", "Price-band measurement and governance"] },
  { slug: "place-data-standard", code: "CON-02", title: "ມາດຕະຖານຂໍ້ມູນສະຖານທີ່", english: "Place Data Standard", category: "content", summary: "ສະບັບ 1.0 ມີ Field Dictionary, Source/Freshness Rules, Place Data Entry Template ແລະ Publish Checklist PUB-01—06 ທີ່ນຳໄປພັດທະນາໄດ້.", status: "approved", sections: ["Field and source rules", "Verification and correction", "Place data entry template", "Publish-readiness checklist"] },
  { slug: "content-acquisition", code: "CON-03", title: "ແຜນຫາ Content ໄລຍະທຳອິດ", english: "Content Acquisition Plan", category: "content", summary: "ສະບັບ 0.9 ມີ Cold-start Gates, Pilot Area Selection Register ແລະ Content Source Ledger; ລໍລະບຸຊື່/ຂອບເຂດ 2–3 ເຂດກ່ອນ 1.0.", status: "in_progress", sections: ["Cold-start inventory and supply gates", "Creator and owner outreach", "Pilot area register", "Content source ledger"] },
  { slug: "creator-moderation", code: "CON-04", title: "Creator ແລະ Content Moderation", english: "Creator & Moderation Guideline", category: "content", summary: "ສະບັບ 1.0 ມີ Reason Codes, P0–P3, Public Intake Forms, Takedown/Appeal Workflow ແລະ Internal Moderation Decision Record.", status: "approved", sections: ["Attribution and eligibility", "Report and takedown", "Public intake forms", "Decision, appeal and audit"] },
  { slug: "legal-disclosure", code: "CON-05", title: "ລິຂະສິດ ແລະ ການເປີດເຜີຍ", english: "Copyright & Sponsored Disclosure", category: "content", summary: "ສະບັບ 0.9 ມີ Linking/Disclosure Policy, Legal Checklist LEG-01—08 ແລະ Consent & Retention Register; ລໍ Legal/TEC-06 ຕື່ມຜົນຕັດສິນກ່ອນ 1.0.", status: "in_progress", sections: ["Linking, takedown and disclosure", "Consent and data boundary", "Legal review checklist", "Consent and retention register"] },

  { slug: "information-user-flow", code: "UX-01", title: "ໂຄງສ້າງຂໍ້ມູນ ແລະ User Flow", english: "Information Architecture & User Flow", category: "design", summary: "ສະບັບ 1.0 ອະນຸມັດ Discover/Search navigation, Should-level Saved, Screen/Route Contract, Internal Correction Form ແລະ Admin Queue Boundary.", status: "approved", sections: ["Navigation model", "Primary user journeys", "Screen and route registry", "Edge cases and recovery"] },
  { slug: "ux-ui-wireframe", code: "UX-02", title: "ໂຄງຮ່າງ UX/UI", english: "UX/UI Wireframe", category: "design", summary: "ສະບັບ 1.2 ອະນຸມັດ Founder Review R2: intent-led Video Search, Place decision page ແລະ category detail ທີ່ມີຮູບລາຍການ, ລາຄາ ແລະ checked date.", status: "approved", sections: ["Full-screen discovery feed", "Intent-led video search", "Place decision page", "Admin screens"] },
  { slug: "interactive-prototype", code: "UX-03", title: "ຕົວຢ່າງໂຕ້ຕອບ", english: "Interactive Prototype & Usability Test", category: "design", summary: "ສະບັບ 0.9.4 ໃຊ້ Prototype R2.3 ທີ່ຜ່ານ Internal Browser QA ແລະ retest ຫຼັງແກ້ 4 findings; ຍັງລໍ external usability evidence ຈາກຜູ້ໃຊ້ 5 ຄົນ.", status: "in_progress", sections: ["Current status and next action", "Founder Review R2 results", "Internal QA evidence", "External test evidence"] },
  { slug: "design-system", code: "UX-04", title: "ລະບົບການອອກແບບ", english: "Design System", category: "design", summary: "ສະບັບ 0.9.4 ບັນທຶກ Internal Browser QA R2.3, finding/fix/retest ແລະ evidence boundary; ຍັງລໍ Physical Keyboard, VoiceOver, Browser Zoom 200% ແລະ OS Reduced Motion ກ່ອນ 1.0. Admin UI ແຍກໄປ UX-04.1.", status: "in_progress", sections: ["Pilot 1.0 and Admin 1.1 boundary", "Tokens and component specifications", "Internal QA findings and retest", "Accessibility evidence and remaining gates"] },
  { slug: "full-ux-ui", code: "UX-05", title: "ການອອກແບບ UX/UI ສົມບູນ", english: "Full UX/UI Design", category: "design", summary: "ສະບັບ 0.11.0 ກຳນົດ Guest/Pilot Prototype R2.3 ແລະ Admin Workflow Prototype R5.0 ເປັນ Design Handoff Baseline. Admin ຄຸ້ມ 10 Modules / 55 views, task-first Content intake, module/sub-menu navigation, view-specific workflow, evidence, export ແລະ session persistence. R5.0 ເພີ່ມ accessible custom dropdown, Lao-readable typography 12–14px, keyboard/touch behavior ແລະ responsive control contract. Visual identity ຍັງອີງ UX-04 Design Tokens. ຍັງລໍ backend/auth/durable persistence, real integrations, exhaustive failure states, Manual Accessibility Gates ແລະ final sign-off ກ່ອນ 1.0.", status: "in_progress", sections: ["Final Design Gallery and interactive prototype", "Admin workflow and interaction contracts", "Developer handoff traceability", "Approval gates and sign-off"] },

  { slug: "system-architecture", code: "TEC-01", title: "ໂຄງສ້າງລະບົບ", english: "System Architecture", category: "technical", summary: "ສະບັບ 1.0 ອະນຸມັດ Modular Monolith-first, 14 logical components, 7 core flows, relational source of truth, queue/outbox, link-only media, server-enforced security ແລະ 4 environments. Pilot RPO 24h / RTO 8h ເປັນຄ່າຊົ່ວຄາວທີ່ຕ້ອງຢືນຢັນໃນ TEC-06.", status: "approved", sections: ["Architecture drivers and system context", "Component, data and integration boundaries", "Deployment, security and recovery", "Decision register and technical handoff"] },
  { slug: "technical-proposal", code: "TEC-02", title: "ຂໍ້ສະເໜີດ້ານເຕັກນິກ", english: "Technical Proposal", category: "technical", summary: "ສະບັບ 1.0 ອະນຸມັດ 2-track delivery, Founder-led Hybrid, Must-only Production Baseline, ການແຍກ Validation Budget ອອກຈາກ Production Build Budget ແລະ 75–110 person-days ເປັນ planning range ພ້ອມ P0—P4 gates. Production budget, team ແລະ delivery date ຍັງຕ້ອງອະນຸມັດຫຼັງ TEC-03/04 ແລະ DEL-01.", status: "approved", sections: ["Two-track proposed solution", "Alternatives and trade-offs", "Effort and cost evidence", "Risk, release gates and handoff"] },
  { slug: "tech-stack", code: "TEC-03", title: "ຊຸດເຕັກໂນໂລຊີ", english: "Tech Stack", category: "technical", summary: "ສະບັບ 1.0 ອະນຸມັດ TypeScript/Next.js 16/Node.js 24 LTS, PostgreSQL 18, Drizzle, PostgreSQL Search, Graphile Worker/Outbox, R2, OIDC ແລະ Vitest/Playwright; ໃຊ້ OVH Dedicated Server Singapore ພ້ອມ Docker Engine CE, Compose v2, BuildKit/buildx, GHCR ແລະ Caddy. Service/network/volume/secret boundary, deployment/rollback, Pino/OpenTelemetry/Grafana Cloud ແລະ SIEM-ready monitoring ຖືກລັອກແລ້ວ; Search/Hosting/Container pre-launch evidence ຍັງຄວບຄຸມຕໍ່ໃນ TEC-05/06.", status: "approved", sections: ["Application and repository baseline", "Data, Lao search and background jobs", "OVH hosting and Container Stack", "Observability, security monitoring, cost and approved decisions"] },
  { slug: "data-api", code: "TEC-04", title: "ຖານຂໍ້ມູນ ແລະ API", english: "Database Design & API Specification", category: "technical", summary: "ສະບັບ 1.0 ອະນຸມັດ physical schema ຈາກ 27 business entities + 3 support tables, key/constraint/index, 31 Public/Admin API catalog entries, stable error, transaction/outbox/idempotency, migration order ແລະ REV-01—05. UUIDv7, LAK/timezone, polymorphic reference controls, API contract ແລະ frozen MVP scope ເປັນ Developer Handoff Baseline.", status: "approved", sections: ["Physical schema and data rules", "Constraints, indexes and search projection", "Public and Admin API contracts", "Transactions, errors, migrations and handoff"] },
  { slug: "ai-recommendation", code: "TEC-05", title: "ການຄົ້ນຫາ ແລະລະບົບແນະນຳ", english: "Search & AI Recommendation", category: "technical", summary: "ສະບັບ 0.1 ກຳນົດ PostgreSQL-first Lao Search, organic ranking ແຍກ Sponsored, cold-start/session-context recommendation, privacy-safe signals, evaluation benchmark ແລະຂັ້ນຕອນຈາກ rule-based ໄປຫາ AI ໂດຍ AI ບໍ່ແມ່ນ MVP dependency.", status: "in_progress", sections: ["Lao normalization and candidate retrieval", "Organic ranking and Sponsored separation", "Cold-start and recommendation phases", "Evaluation, monitoring, safeguards and AI escalation"] },
  { slug: "security-infrastructure", code: "TEC-06", title: "Security, Privacy ແລະ Infrastructure", english: "Security, Privacy & Infrastructure", category: "technical", summary: "ຄວບຄຸມສິດ, ຂໍ້ມູນສ່ວນຕົວ, backup, monitoring, server cost ແລະ disaster recovery.", status: "planned", sections: ["Threat and privacy model", "Access control", "Infrastructure cost", "Backup and recovery"] },

  { slug: "development-plan", code: "DEL-01", title: "ແຜນການພັດທະນາ", english: "Development Plan", category: "delivery", summary: "ແບ່ງ milestone, sprint, team, dependency, budget ແລະ deliverable ຈາກ MVP ເຖິງ launch.", status: "next", sections: ["Milestones and sprints", "Team and ownership", "Dependencies", "Deliverables"] },
  { slug: "test-uat", code: "DEL-02", title: "ແຜນທົດສອບ ແລະ UAT", english: "Test & UAT Plan", category: "delivery", summary: "ກຳນົດ unit, integration, usability, performance, security ແລະການຮັບມອບຈາກຝ່າຍທຸລະກິດ.", status: "planned", sections: ["Test levels", "Critical scenarios", "UAT process", "Exit criteria"] },
  { slug: "release-monitoring", code: "DEL-03", title: "Release ແລະ Monitoring", english: "Deployment, Release & Monitoring", category: "delivery", summary: "ກຳນົດ environment, CI/CD, release checklist, rollback, alert ແລະ incident response.", status: "planned", sections: ["Environments", "Release process", "Monitoring and alerts", "Rollback and incidents"] },
  { slug: "analytics-plan", code: "DEL-04", title: "ແຜນເກັບ Analytics", english: "Analytics Tracking Plan", category: "delivery", summary: "ລະບຸ event ຕັ້ງແຕ່ video view ຫາ map/call click ເພື່ອວັດ funnel ແລະລາຍຮັບ.", status: "planned", sections: ["Event taxonomy", "Funnel definition", "Data quality", "Dashboards"] },
  { slug: "admin-operations", code: "DEL-05", title: "ຄູ່ມື Admin ແລະການດຳເນີນງານ", english: "Admin & Operations SOP", category: "delivery", summary: "ກຳນົດວິທີກວດ place, moderation, support, correction, escalation ແລະ maintenance.", status: "planned", sections: ["Daily operations", "Moderation and support", "Escalation", "Maintenance cadence"] },
];

export const getDocument = (slug: string) => documents.find((document) => document.slug === slug);
